const sampleSongs = [
  { song: "소나기", artist: "아이오아이 (I.O.I)" },
  { song: "미워요", artist: "정인" },
  { song: "신촌을 못가", artist: "포스트맨 (Postmen)" },
  { song: "가질수 없는 너", artist: "뱅크" },
  { song: "술 한잔 해요", artist: "지아 (Zia)" },
  { song: "눈의 꽃", artist: "박효신" },
  { song: "지우개", artist: "알리 (Ali)" },
  { song: "오르막길", artist: "정인, 윤종신" },
  { song: "그녀를 찾아주세요", artist: "더 네임 (The Name)" },
  { song: "걱정말아요 그대", artist: "이적" },
  { song: "물감", artist: "문문 (MoonMoon)" },
  { song: "인연", artist: "이선희" },
  { song: "바람기억", artist: "나얼" },
  { song: "겨울을 걷는다", artist: "윤딴딴" },
  { song: "보고싶다", artist: "김범수" },
  { song: "바보에게 바보가", artist: "박명수" },
  { song: "퇴근버스", artist: "이준호" },
  { song: "내가 저지른 사랑", artist: "임창정" },
  { song: "행복하지 말아요", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "야생화", artist: "박효신" },
  { song: "가시", artist: "버즈 (Buzz)" },
  { song: "이 소설의 끝을 다시 써보려 해", artist: "한동근" },
  { song: "체념", artist: "빅마마 (Big Mama)" },
  { song: "스토커", artist: "10cm" },
  { song: "Tears", artist: "소찬휘" },
  { song: "One Love", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "Hello", artist: "허각" },
  { song: "그대라는 사치", artist: "한동근" },
  { song: "응급실", artist: "이지 (izi)" },
  { song: "소주 한잔", artist: "임창정" },
  { song: "안아줘", artist: "정준일" },
  { song: "Marry Me", artist: "구윤회" },
  { song: "키보드 (Prod. By Hansen)", artist: "기리보이 (Giriboy)" },
  { song: "Believer", artist: "Imagine Dragons" },
  { song: "If You Were Me", artist: "벤(Ben)" },
  { song: "Wow Thing", artist: "슬기 (SEULGI), 신비, 청하, 소연" },
  { song: "Perfect", artist: "10cm" },
  { song: "정인 (情人)", artist: "세정" },
  { song: "이별하러 가는 길", artist: "임한별" },
  {
    song: "IndiGO",
    artist: "저스디스 (JUSTHIS), Kid Milli, NO:EL, 영비 (Young B)",
  },
  { song: "열애중 (답가)", artist: "하은" },
  { song: "유재석 (prod. 진대호)", artist: "빈첸 (VINXEN)" },
  { song: "별 (Feat. 김종완 of 넬) (prod.BOYCOLD)", artist: "빈첸 (VINXEN)" },
  { song: "도망가지마", artist: "모트 (Motte)" },
  { song: "가을 타나 봐", artist: "바이브 (Vibe)" },
  { song: "하루도 그대를 사랑하지 않은 적이 없었다", artist: "임창정" },
  { song: "우리 그만하자", artist: "로이킴" },
  { song: "지워져", artist: "거미" },
  { song: "사랑에 아파본 적 있나요", artist: "스탠딩 에그 (Standing Egg)" },
  { song: "셀 수 없는 (Countless)", artist: "샤이니 (SHINee)" },
  { song: "We Young", artist: "찬열, 세훈" },
  { song: "V", artist: "박재범" },
  { song: "노래", artist: "김동률" },
  { song: "불꽃놀이 (Remember Me)", artist: "오마이걸 (OH MY GIRL)" },
  { song: "잘 지내요", artist: "정승환" },
  { song: "헤어지는 중", artist: "펀치 (Punch)" },
  { song: "사이렌 (Siren)", artist: "선미" },
  { song: "너만 괜찮다면", artist: "남우현" },
  { song: "We Go Up", artist: "NCT DREAM" },
  { song: "NOAH (Feat. 박재범, Hoody)", artist: "김하온 (HAON)" },
  { song: "See You Again (Feat. 리처드 용재 오닐)", artist: "백지영" },
  { song: "몰랐니 (Lil’ Touch)", artist: "소녀시대-Oh!GG" },
  { song: "사이렌(Siren)", artist: "선미" },
  { song: "Kiss Me Like That", artist: "신화" },
  { song: "AND I", artist: "뉴이스트 W" },
  { song: "YOUNG", artist: "백현 (BAEKHYUN), 로꼬" },
  { song: "Vacation (Feat. SOLE)", artist: "개코 (GAEKO)" },
  { song: "늘 그대", artist: "양희은, 성시경" },
  { song: "I AM", artist: "새벽 한 시" },
  { song: "IDOL (Feat. Nicki Minaj)", artist: "방탄소년단" },
  {
    song: "스무살이 왜이리 능글맞아 (Feat. 숀 (SHAUN))",
    artist: "오반 (OVAN)",
  },
  { song: "다시 만나 (See you again)", artist: "약속" },
  { song: "Serendipity (Full Length Edition)", artist: "방탄소년단" },
  { song: "미워도 다시 한 번", artist: "벤(Ben)" },
  { song: "10", artist: "Summer Wish" },
  { song: "Rollin` Rollin`", artist: "러브포션" },
  { song: "Trivia 承 : Love", artist: "방탄소년단" },
  { song: "Trivia 轉 : Seesaw", artist: "방탄소년단" },
  { song: "왜 몰랐을까", artist: "로이킴" },
  { song: "너에게 닿기를 (To reach you)", artist: "기억 조작단" },
  { song: "Power", artist: "EXO" },
  { song: "어디에도", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "HOLIDAY (Feat. DPR LIVE)", artist: "수지" },
  { song: "덜덜덜", artist: "EXID" },
  { song: "Ko Ko Bop", artist: "EXO" },
  { song: "눈 (Feat. 이문세)", artist: "자이언티(Zion.T)" },
  { song: "별", artist: "양요섭" },
  { song: "겨울소리", artist: "박효신" },
  { song: "애쓰지 마요", artist: "박보람" },
  { song: "고민보다 Go", artist: "방탄소년단" },
  { song: "팔레트 (Feat. G-DRAGON)", artist: "아이유 (IU)" },
  { song: "다시 쓰고 싶어", artist: "에일리 (Ailee)" },
  { song: "매일 듣는 노래 (A Daily Song)", artist: "황치열" },
  { song: "한숨", artist: "이하이" },
  { song: "Blue", artist: "볼빨간 사춘기" },
  { song: "미안해", artist: "양다일" },
  { song: "그 사람을 아나요", artist: "임창정" },
  { song: "Closer (Feat. Halsey)", artist: "The Chainsmokers" },
  { song: "Universe", artist: "EXO" },
  { song: "Thunder", artist: "Imagine Dragons" },
  { song: "바람이 불었으면 좋겠어", artist: "길구봉구" },
  { song: "에너제틱 (Energetic)", artist: "Wanna One (워너원)" },
  { song: "REALLY REALLY", artist: "위너(WINNER)" },
  { song: "비밀정원", artist: "오마이걸 (OH MY GIRL)" },
  { song: "나의 사춘기에게", artist: "볼빨간 사춘기" },
  { song: "네가 없는 곳", artist: "양요섭" },
  { song: "고맙다", artist: "세븐틴" },
  { song: "마지막처럼", artist: "BLACKPINK" },
  { song: "짙어져", artist: "멜로망스(MeloMance)" },
  { song: "바보야", artist: "허각" },
  { song: "Lonely (Feat. 태연)", artist: "종현 (JONGHYUN)" },
  { song: "연애소설 (Feat. 아이유)", artist: "에픽하이 (EPIK HIGH)" },
  { song: "오늘밤도", artist: "펀치 (Punch)" },
  { song: "비가 온다", artist: "정승환" },
  { song: "빨간 맛 (Red Flavor)", artist: "레드벨벳(Red Velvet)" },
  { song: "빛 (Hope)", artist: "H.O.T" },
  { song: "가시나", artist: "선미" },
  { song: "노력", artist: "박원" },
  { song: "봄날", artist: "방탄소년단" },
  { song: "Beautiful", artist: "Wanna One (워너원)" },
  { song: "첫눈처럼 너에게 가겠다", artist: "에일리 (Ailee)" },
  { song: "그때의 나, 그때의 우리", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "후유증", artist: "김희철, 민경훈" },
  { song: "비도 오고 그래서 (Feat. 신용재)", artist: "헤이즈 (Heize)" },
  { song: "There`s Nothing Holdin` Me Back", artist: "Shawn Mendes" },
  { song: "썸 탈꺼야", artist: "볼빨간 사춘기" },
  { song: "너 없는 시간들", artist: "다비치" },
  { song: "True Love", artist: "김성규" },
  { song: "You", artist: "멜로망스(MeloMance)" },
  { song: "좋아", artist: "윤종신, 민서" },
  { song: "눈 떠보니 이별이더라", artist: "포맨 (4Men)" },
  { song: "시차 (We Are) (Feat. 로꼬 & GRAY)", artist: "우원재" },
  { song: "가을 안부", artist: "먼데이키즈 (Monday Kiz)" },
  { song: "그리워하다", artist: "비투비 (BTOB)" },
  { song: "답장", artist: "김동률" },
  { song: "기억의 빈자리", artist: "나얼" },
  { song: "피카부 (Peek-A-Boo)", artist: "레드벨벳(Red Velvet)" },
  { song: "밤편지", artist: "아이유 (IU)" },
  { song: "Shape of You", artist: "Ed Sheeran" },
  { song: "My Way", artist: "이수" },
  { song: "LIKEY", artist: "TWICE" },
  { song: "DNA", artist: "방탄소년단" },
  { song: "다른사람을 사랑하고 있어", artist: "수지" },
  { song: "all of my life", artist: "박원" },
  { song: "좋니", artist: "윤종신" },
  { song: "이 별", artist: "길구봉구" },
  { song: "Heart Shaker", artist: "TWICE" },
  { song: "밤이 되니까", artist: "펀치 (Punch)" },
  { song: "#첫사랑", artist: "볼빨간 사춘기" },
  { song: "instagram", artist: "DEAN" },
  { song: "주인공", artist: "선미" },
  { song: "비행운", artist: "문문 (MoonMoon)" },
  { song: "눈사람", artist: "정승환" },
  { song: "HandClap", artist: "Fitz & The Tantrums" },
  { song: "선물", artist: "멜로망스(Melomance)" },
  { song: "Havana (Feat. Young Thug)", artist: "Camila Cabello" },
  { song: "Roller Coaster", artist: "청하" },
  { song: "Bad Boy", artist: "레드벨벳(Red Velvet)" },
  { song: "그날처럼", artist: "장덕철" },
  { song: "그때 헤어지면 돼", artist: "로이킴" },
  { song: "뿜뿜", artist: "모모랜드 (MOMOLAND)" },
  { song: "붕붕 (Feat. Sik-K) (Prod. GroovyRoom)", artist: "김하온 (HAON)" },
  { song: "Adios (Prod. BOYCOLD)", artist: "김하온 (HAON)" },
  { song: "花요일 (Blooming Day)", artist: "EXO-CBX (첸백시)" },
  { song: "What is Love?", artist: "TWICE" },
  { song: "LA LA", artist: "WINNER" },
  { song: "여보세요 (HELLO)", artist: "WINNER" },
  { song: "예뻤더라 (WE WERE)", artist: "WINNER" },
  { song: "아름다운 (Feat. 헤이즈)", artist: "신용재" },
  { song: "탓 (Prod. BOYCOLD)", artist: "이병재 (Vinxen)" },
  { song: "그대니까요", artist: "다비치" },
  {
    song: "MADMAX (Feat. Woodie Gochild) (Prod. GroovyRoom)",
    artist: "박준호 (PULLIK)",
  },
  { song: "손만 잡고 자자 (TURN OFF THE LIGHT) (MINO SOLO)", artist: "WINNER" },
  { song: "넋두리", artist: "닐로 (Nilo)" },
  { song: "AIR", artist: "WINNER" },
  { song: "Young Wave (Feat. 행주, 보이비)", artist: "오담률 (CHIN CHILLA)" },
  { song: "내일해", artist: "EXID" },
  { song: "EVERYDAY", artist: "WINNER" },
  { song: "봄이 좋냐??", artist: "10cm" },
  { song: "매일 봐요", artist: "마마무 (Mamamoo)" },
  { song: "하루끝엔 그대가 있어요", artist: "한동근" },
  { song: "Someone like you", artist: "EXO-CBX (첸백시)" },
  { song: "널 부르는 밤", artist: "나얼" },
  { song: "봄 사랑 벚꽃 말고", artist: "HIGH4, 아이유 (IU)" },
  { song: "남겨둘게 (Feat. 헤이즈)", artist: "키썸 (Kisum)" },
  { song: "그럴 수밖에", artist: "김동률" },
  { song: "지나오다", artist: "닐로 (Nilo)" },
  {
    song: "바코드 (Prod. GroovyRoom)",
    artist: "김하온 (HAON), 이병재 (Vinxen)",
  },
  { song: "운명 (The Chance of Love)", artist: "동방신기" },
  {
    song: "Like It (Feat. 행주, 보이비)",
    artist: "배연서 (WEBSTER B), 윤진영(Clloud)",
  },
  { song: "비", artist: "폴킴" },
  { song: "어린 왕자 (Prod. Godic)", artist: "김하온(HAON), 박준호(PULLIK)" },
  { song: "껍데기는 가", artist: "김근수, 조원우 (H2ADIN)" },
  { song: "모든 날, 모든 순간 (Every day, Every Moment)", artist: "폴킴" },
  { song: "약속해요 (고백 Ver.)", artist: "Wanna One (워너원)" },
  { song: "WE ARE", artist: "Wanna One (워너원)" },
  { song: "보여", artist: "Wanna One (워너원)" },
  { song: "너의 이름을", artist: "Wanna One (워너원)" },
  { song: "GOLD", artist: "Wanna One (워너원)" },
  { song: "소나기 (Feat. 10cm)", artist: "용준형" },
  { song: "BOOMERANG (부메랑)", artist: "Wanna One (워너원)" },
  { song: "북 (Prod.SLO)", artist: "배연서 (WEBSTER B), 오담률 (CHIN CHILLA)" },
  { song: "BOSS", artist: "NCT U" },
  { song: "결혼", artist: "문문 (MoonMoon)" },
  { song: "실례해도 될까요", artist: "장재인, 수호(SUHO)" },
  { song: "Action! (Feat. GRAY)", artist: "DPR LIVE" },
  { song: "벚꽃 엔딩", artist: "버스커 버스커 (Busker Busker)" },
  { song: "My Blossom", artist: "소유" },
  { song: "나타나줘 (Feat. 박재범)", artist: "로꼬 (LOCO)" },
  { song: "Look", artist: "GOT7" },
  { song: "꽃 길", artist: "빅뱅" },
  { song: "She`s gone", artist: "정일훈" },
  { song: "갖고 싶어", artist: "Wanna One (워너원)" },
  { song: "바람", artist: "헤이즈 (Heize)" },
  { song: "다시", artist: "이상순" },
  { song: "그날의 너에게", artist: "노을" },
  { song: "MIANHAE", artist: "헤이즈 (Heize)" },
  { song: "잘 살길 바래 (With. DAVII)", artist: "헤이즈 (Heize)" },
  { song: "별 바람 꽃 태양", artist: "마마무 (Mamamoo)" },
  { song: "고무줄다리기 (Rubber Band)", artist: "iKON" },
  { song: "괜찮냐고", artist: "헤이즈 (Heize)" },
  { song: "내가 더 나빠", artist: "헤이즈 (Heize)" },
  { song: "약속해요 (I.P.U.)", artist: "Wanna One (워너원)" },
  { song: "Jenga (Feat. Gaeko)", artist: "헤이즈 (Heize)" },
  { song: "별이 빛나는 밤", artist: "마마무 (Mamamoo)" },
  { song: "오늘 취하면 (Feat.창모) (Prod. SUGA)", artist: "수란 (SURAN)" },
  { song: "What Lovers Do (Feat. SZA)", artist: "Maroon 5" },
  { song: "널 너무 모르고", artist: "헤이즈 (Heize)" },
  { song: "사랑하지 않은 것처럼", artist: "버즈 (Buzz)" },
  { song: "너였다면", artist: "정승환" },
  { song: "LONG TIME NO SEE", artist: "iKON" },
  { song: "Love Yourself", artist: "Justin Bieber" },
  { song: "폰서트", artist: "10cm" },
  { song: "빛이 나 (Shinin`)", artist: "종현 (JONGHYUN)" },
  { song: "가을 아침", artist: "아이유 (IU)" },
  { song: "너 하나만 (Feat. 효린)", artist: "GOT7" },
  { song: "피 땀 눈물", artist: "방탄소년단" },
  { song: "Something Just Like This", artist: "The Chainsmokers, Coldplay" },
  { song: "행복 (Full Of Happiness)", artist: "H.O.T" },
  { song: "MIC Drop", artist: "방탄소년단" },
  { song: "Tell Me", artist: "인피니트 (Infinite)" },
  { song: "남이 될 수 있을까", artist: "볼빨간 사춘기, 스무살" },
  { song: "봉제선 (Feat. 수란)", artist: "다이나믹 듀오 (Dynamic Duo)" },
  { song: "Youth", artist: "Troye Sivan" },
  { song: "I Want You", artist: "샤이니 (SHINee)" },
  { song: "The Feeling", artist: "비투비 (BTOB)" },
  { song: "Forever Young", artist: "BLACKPINK" },
  { song: "뚜두뚜두 (DDU-DU DDU-DU)", artist: "BLACKPINK" },
  { song: "FAKE LOVE (Rocking Vibe Mix)", artist: "방탄소년단" },
  { song: "11 (Prod. 다이나믹듀오)", artist: "Wanna One (워너원) - 남바완" },
  { song: "영원+1 (Prod. NELL)", artist: "Wanna One (워너원) - 린온미" },
  { song: "모래시계 (Prod. 헤이즈)", artist: "Wanna One (워너원) - 더힐" },
  {
    song: "캥거루 (Kangaroo) (Prod. ZICO)",
    artist: "Wanna One (워너원) - 트리플포지션",
  },
  { song: "켜줘 (Light)", artist: "Wanna One (워너원)" },
  { song: "안녕 (You & I)", artist: "샤이니 (SHINee)" },
  { song: "All Day All Night", artist: "샤이니 (SHINee)" },
  { song: "영원히", artist: "성시경" },
  { song: "이 밤의 끝", artist: "펀치 (Punch)" },
  { song: "다시, 우리", artist: "길구봉구" },
  { song: "LOVE YA!", artist: "혁오 (hyukoh)" },
  { song: "데리러 가 (Good Evening)", artist: "샤이니 (SHINee)" },
  { song: "빙글뱅글 (Bingle Bangle)", artist: "AOA" },
  { song: "Lullaby", artist: "신승훈, 비와이(BewhY)" },
  { song: "SELFISH (Feat. 슬기 Of Red Velvet)", artist: "문별" },
  { song: "Clip", artist: "볼빨간사춘기" },
  { song: "안녕, 곰인형", artist: "볼빨간사춘기" },
  { song: "야경", artist: "볼빨간사춘기" },
  { song: "Lonely", artist: "볼빨간사춘기" },
  { song: "바람사람", artist: "볼빨간사춘기" },
  { song: "여행", artist: "볼빨간사춘기" },
  { song: "열애중", artist: "벤 (Ben)" },
  { song: "Outro : Tear", artist: "방탄소년단" },
  { song: "Additional", artist: "폴킴" },
  { song: "Intro : Singularity", artist: "방탄소년단" },
  { song: "Fly Away", artist: "신승훈, 에일리" },
  { song: "So What", artist: "방탄소년단" },
  { song: "Airplane pt.2", artist: "방탄소년단" },
  { song: "Anpanman", artist: "방탄소년단" },
  { song: "Magic Shop", artist: "방탄소년단" },
  { song: "Love Maze", artist: "방탄소년단" },
  { song: "낙원", artist: "방탄소년단" },
  { song: "134340", artist: "방탄소년단" },
  { song: "전하지 못한 진심 (Feat. Steve Aoki)", artist: "방탄소년단" },
  { song: "FAKE LOVE", artist: "방탄소년단" },
  { song: "우리 서로", artist: "김나영" },
  { song: "너란 별", artist: "케이윌 (K.Will)" },
  { song: "그대들은 어떤 기분이신가요", artist: "빈첸 (VINXEN)" },
  { song: "SINKING DOWN WITH U", artist: "빈첸 (VINXEN)" },
  { song: "무슨 말이 필요해 (Go Away)", artist: "용준형" },
  { song: "LATATA", artist: "(여자)아이들" },
  { song: "우리 둘만 아는", artist: "윤건" },
  { song: "뒤집어버려", artist: "박재범,사이먼 도미닉,로꼬,그레이(GRAY)" },
  { song: "빛나리", artist: "펜타곤 (PENTAGON)" },
  { song: "My Paradise (Feat. 청하, VINXEN)", artist: "GroovyRoom (그루비룸)" },
  { song: "잊을만하면", artist: "크러쉬 (CRUSH)" },
  { song: "밤 (Time for the moon night)", artist: "여자친구 (GFRIEND)" },
  { song: "별 시 (別 時)", artist: "박효신" },
  {
    song: "Graduation (Feat. 이병재 (VINXEN), 이로한 (WEBSTER B))",
    artist: "김하온 (HAON)",
  },
  { song: "달리 (Dally) (Feat. GRAY)", artist: "효린" },
  { song: "별, 그대 (The Only Star)", artist: "황치열" },
  { song: "그날의 너", artist: "러블리즈" },
  { song: "욕심", artist: "멜로망스(MeloMance)" },
  { song: "어른", artist: "Sondia" },
  {
    song: "YAHO (Feat. 지구인, 행주) (Prod. Jangsoo, Padi)",
    artist: "윤진영 (Clloud)",
  },
  { song: "부를게", artist: "JBJ" },
  { song: "주지마", artist: "로꼬, 화사" },
  { song: "#결별", artist: "길구봉구, 박보람" },
  { song: "향 (Scentist)", artist: "빅스 (VIXX)" },
  { song: "EASY (Feat. 식케이)", artist: "휘인" },
  { song: "휴일 (Lazy)", artist: "EXO-CBX (첸백시)" },
  { song: "Thursday", artist: "EXO-CBX (첸백시)" },
  { song: "솔직히 (Honestly…)", artist: "에릭남" },
  { song: "Vroom Vroom", artist: "EXO-CBX (첸백시)" },
  { song: "Monday Blues", artist: "EXO-CBX (첸백시)" },
  { song: "너에게 꽃이다", artist: "40 (포티)" },
  { song: "내일 만나 (Sweet Dreams!)", artist: "EXO-CBX (첸백시)" },
  { song: "Why Why Why", artist: "펀치 (Punch)" },
  {
    song: "이로한 (Feat. ELO, Jessi) (Prod. Padi)",
    artist: "배연서 (WEBSTER B)",
  },
  { song: "Playdate", artist: "EXO-CBX (첸백시)" },
  { song: "전혀 (Feat. 우원재) (Prod. GroovyRoom)", artist: "이병재 (Vinxen)" },
  { song: "Stand By Your Man", artist: "Carla Bruni" },
  { song: "Trivia 起 : Just Dance", artist: "방탄소년단" },
  { song: "Epiphany", artist: "방탄소년단" },
  { song: "Answer : Love Myself", artist: "방탄소년단" },
  { song: "I`m Fine", artist: "방탄소년단" },
  { song: "Rumor", artist: "국.슈 (국프의 핫이슈)" },
  { song: "Euphoria", artist: "방탄소년단" },
  { song: "IDOL", artist: "방탄소년단" },
  { song: "매트리스", artist: "10cm" },
  { song: "BAE", artist: "효린" },
  { song: "Attention", artist: "Charlie Puth" },
  { song: "이방인", artist: "박원" },
  { song: "A-TEEN", artist: "세븐틴" },
  { song: "한(一)", artist: "(여자)아이들" },
  { song: "Mosquito", artist: "레드벨벳(Red Velvet)" },
  { song: "Hit That Drum", artist: "레드벨벳(Red Velvet)" },
  { song: "Mr. E", artist: "레드벨벳(Red Velvet)" },
  { song: "Page 0", artist: "태연 (TAEYEON), 멜로망스(Melomance)" },
  { song: "Blue Lemonade", artist: "레드벨벳(Red Velvet)" },
  { song: "휴가", artist: "폴킴" },
  { song: "태양 (Feat. 챈슬러)", artist: "개리 (Gary)" },
  { song: "좋은 날", artist: "멜로망스(MeloMance)" },
  { song: "한 여름의 크리스마스 (With You)", artist: "레드벨벳(Red Velvet)" },
  { song: "Power Up", artist: "레드벨벳(Red Velvet)" },
  {
    song: "flex (Prod. By 기리보이)",
    artist: "기리보이,Kid Milli,NO:EL,스윙스(Swings)",
  },
  { song: "소리", artist: "이수현" },
  { song: "비가 내리면", artist: "비투비-블루" },
  { song: "죽겠다 (KILLING ME)", artist: "iKON" },
  { song: "SoulMate (Feat. 아이유)", artist: "지코 (ZICO)" },
  { song: "여보세요", artist: "뉴이스트 (NU`EST)" },
  { song: "20 Something (PROD. 정동환, 정세운)", artist: "정세운" },
  { song: "WHERE R U FROM (Feat. MINO)", artist: "승리" },
  { song: "바다보러갈래 (SEE SEA)", artist: "효린" },
  { song: "Me No Jay Park", artist: "사이먼 도미닉 (Simon Dominic)" },
  { song: "나에게로 와", artist: "세븐틴" },
  { song: "여름밤의 꿈 (Midnight Summer Dream)", artist: "마마무 (Mamamoo)" },
  { song: "우리의 새벽은 낮보다 뜨겁다", artist: "세븐틴" },
  { song: "Holiday", artist: "세븐틴" },
  { song: "6 o`clock", artist: "볼빨간 사춘기" },
  { song: "셋 셀테니 (1, 2, 3!)", artist: "승리" },
  { song: "여름여름해 (Sunny Summer)", artist: "여자친구 (GFRIEND)" },
  { song: "어쩌나", artist: "세븐틴" },
  { song: "Love U", artist: "청하" },
  { song: "너나 해 (Egotistic)", artist: "마마무 (Mamamoo)" },
  { song: "그해 여름", artist: "양다일, 웬디 (WENDY)" },
  { song: "Chandelier", artist: "Sia" },
  { song: "Cereal (Feat. ZICO)", artist: "크러쉬 (CRUSH)" },
  { song: "CHILLAX", artist: "TWICE" },
  { song: "지각", artist: "장덕철" },
  { song: "마치 우린 없었던 사이 (Prod. 정키)", artist: "다비치" },
  { song: "그 날 (Original Ver.)", artist: "박효신" },
  { song: "Way Back Home", artist: "숀 (SHAUN)" },
  { song: "장마", artist: "마마무 (Mamamoo)" },
  { song: "동화", artist: "멜로망스 (MeloMance)" },
  { song: "1도 없어", artist: "에이핑크 (Apink)" },
  { song: "Dance The Night Away", artist: "TWICE" },
  { song: "Lock You Down (Special Track)", artist: "샤이니 (SHINee)" },
  { song: "Shadow", artist: "뉴이스트 W" },
  { song: "중력달 (Gravity&Moon)", artist: "뉴이스트 W" },
  { song: "ylenoL", artist: "뉴이스트 W" },
  { song: "Signal", artist: "뉴이스트 W" },
  { song: "그대만 보여서", artist: "김나영" },
  { song: "북극성 (Polaris)", artist: "뉴이스트 W" },
  { song: "네가 남겨둔 말 (Our Page)", artist: "샤이니 (SHINee)" },
  { song: "BAAM", artist: "모모랜드 (MOMOLAND)" },
  { song: "Dejavu", artist: "뉴이스트 W" },
  { song: "1, 2, 3", artist: "서은광, 이창섭, 임현식, 육성재" },
  { song: "정진철", artist: "사이먼 도미닉 (Simon Dominic)" },
  { song: "Yeah", artist: "비투비 (BTOB)" },
  { song: "길에서", artist: "양요섭" },
  { song: "Circus", artist: "태연 (TAEYEON)" },
  {
    song: "귀가본능 (Feat. JINBO the superfreak)",
    artist: "사이먼 도미닉 (Simon Dominic)",
  },
  { song: "불행 (Feat. 빈첸 (VINXEN))", artist: "오반 (OVAN)" },
  { song: "Call me", artist: "비투비 (BTOB)" },
  {
    song: "저녁의 이유 (All Night Long) (Feat. LUCAS of NCT)",
    artist: "태연 (TAEYEON)",
  },
  { song: "Blue Moon", artist: "비투비 (BTOB)" },
  { song: "Something New", artist: "태연 (TAEYEON)" },
  { song: "너 없인 안 된다", artist: "비투비 (BTOB)" },
  { song: "LOVE", artist: "린(LYn),한해" },
  { song: "See U Later", artist: "BLACKPINK" },
  { song: "질투나", artist: "거미, 에일리" },
  { song: "Really", artist: "BLACKPINK" },
  { song: "오늘은 가지마", artist: "임세준" },
  { song: "사랑비", artist: "김태우" },
  { song: "혼자, 한잔", artist: "허각" },
  { song: "노래가 늘었어", artist: "에일리 (Ailee)" },
  { song: "비밀번호 486", artist: "윤하" },
  { song: "보여줄게", artist: "에일리 (Ailee)" },
  { song: "Endless", artist: "플라워 (Flower)" },
  { song: "눈, 코, 입", artist: "태양" },
  { song: "...사랑했잖아", artist: "린 (LYn)" },
  { song: "그립고 그립고 그립다", artist: "케이윌 (K.will)" },
  { song: "취하고 싶다 (Prod. By 전태익)", artist: "황인욱" },
  { song: "그대를 사랑하는 10가지 이유", artist: "이석훈" },
  { song: "서울의 달", artist: "김건모" },
  { song: "애상", artist: "10cm" },
  { song: "오래된 노래", artist: "스탠딩 에그(Standing Egg)" },
  { song: "사랑했지만", artist: "김광석" },
  { song: "끝사랑", artist: "김범수" },
  { song: "꿈에", artist: "박정현" },
  { song: "사랑했었다 (Still love you)", artist: "이홍기, 유회승" },
  { song: "홍연", artist: "안예은" },
  { song: "사랑합니다", artist: "팀 (Tim)" },
  { song: "사랑의 배터리", artist: "홍진영" },
  { song: "미인 (美人)", artist: "이기찬" },
  { song: "그녀를 사랑해줘요", artist: "하동균" },
  { song: "범퍼카 (Feat. NO:EL, Young B)", artist: "한요한" },
  { song: "고백", artist: "정준일" },
  { song: "꽃피는 봄이 오면", artist: "BMK" },
  { song: "헤어지는 중입니다", artist: "이은미" },
  { song: "봄봄봄", artist: "로이킴" },
  { song: "Officially Missing You", artist: "긱스 (Geeks)" },
  { song: "서쪽 하늘", artist: "울랄라세션" },
  { song: "내가 너의 곁에 잠시 살았다는 걸", artist: "토이 (Toy), 김연우" },
  { song: "불장난", artist: "BLACKPINK" },
  { song: "기다릴게", artist: "하동균, 이정" },
  { song: "정류장", artist: "버스커 버스커 (Busker Busker)" },
  { song: "기다리다", artist: "윤하" },
  { song: "널 사랑하지 않아", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "너를 위해", artist: "임재범" },
  { song: "듣는편지", artist: "40 (포티)" },
  { song: "입술의 말", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "애인... 있어요", artist: "이은미" },
  { song: "이별택시", artist: "김연우" },
  { song: "시간을 거슬러", artist: "린 (LYn)" },
  { song: "남자를 몰라", artist: "버즈 (Buzz)" },
  { song: "캔디 (Candy)", artist: "H.O.T" },
  { song: "첫 눈", artist: "정준일" },
  { song: "Let It Go", artist: "Idina Menzel" },
  { song: "친구라도 될 걸 그랬어", artist: "거미" },
  { song: "잠시만 안녕 (Original)", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "바라보기", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "감사", artist: "김동률" },
  { song: "광화문에서 (At Gwanghwamun)", artist: "규현 (KYUHYUN)" },
  { song: "1월부터 6월까지", artist: "윤종신" },
  { song: "이미 슬픈 사랑", artist: "야다 (Yada)" },
  { song: "잊지 말아요", artist: "백지영" },
  { song: "나를 사랑했던 사람아", artist: "허각" },
  { song: "천년의 사랑", artist: "박완규" },
  { song: "나비잠 (Sweet Dream)", artist: "희철, 민경훈" },
  {
    song: "노땡큐 (Feat. MINO, 사이먼 도미닉, 더콰이엇)",
    artist: "에픽하이 (EPIK HIGH)",
  },
  { song: "8282", artist: "다비치" },
  { song: "형 (兄)", artist: "노라조" },
  { song: "삭제", artist: "이승기" },
  { song: "죽일 놈 (Guilty)", artist: "다이나믹 듀오 (Dynamic Duo)" },
  { song: "가족사진", artist: "김진호" },
  { song: "사랑을 했다 (LOVE SCENARIO)", artist: "iKON" },
  {
    song: "flex (Prod. By 기리보이)",
    artist: "기리보이, Kid Milli, NO:EL, 스윙스 (Swings)",
  },
  {
    song: "No Brainer (Feat. Justin Bieber, Chance the Rapper & Quavo)",
    artist: "DJ Khaled",
  },
  { song: "EX", artist: "Kiana Lede" },
  { song: "#첫사랑", artist: "볼빨간사춘기" },
  { song: "The Middle", artist: "Zedd, Grey, Maren Morris" },
  { song: "Idontwannabeyouanymore", artist: "Billie Eilish" },
  { song: "좋았을걸", artist: "헤이즈 (Heize)" },
  { song: "How Long", artist: "Charlie Puth" },
  { song: "잘가라", artist: "홍진영" },
  { song: "바보에게 바보가", artist: "지아 (Zia)" },
  { song: "자격지심 (Feat. 은하 of 여자친구)", artist: "박경" },
  { song: "아마도 그건", artist: "크러쉬 (CRUSH), 로꼬(LOCO)" },
  { song: "Despacito", artist: "제이플라 (J.Fla)" },
  { song: "This Christmas", artist: "태연 (TAEYEON)" },
  { song: "Best Of Me", artist: "방탄소년단" },
  { song: "24K Magic", artist: "Bruno Mars" },
  { song: "Stay", artist: "Zedd, Alessia Cara" },
  { song: "iffy (Prod. GroovyRoom)", artist: "Sik-K (식케이), pH-1, 박재범" },
  { song: "Never Be The Same", artist: "Camila Cabello" },
  { song: "무제(無題) (Untitled, 2014)", artist: "G-Dragon" },
  { song: "Bad", artist: "Christopher" },
  { song: "One Kiss", artist: "Calvin Harris, Dua Lipa" },
  { song: "WHERE YOU AT", artist: "뉴이스트 W" },
  { song: "Selfmade Orange (Feat. SUPERBEE)", artist: "창모 (CHANGMO)" },
  { song: "Girls Like You (Feat. Cardi B)", artist: "Maroon 5" },
  { song: "FRIENDS", artist: "Marshmello, Anne-Marie" },
  { song: "Black Swan", artist: "방탄소년단" },
  { song: "아무노래", artist: "지코 (ZICO)" },
  { song: "다시 난, 여기", artist: "백예린" },
  { song: "너를 사랑하고 있어", artist: "백현 (BAEKHYUN)" },
  { song: "Psycho", artist: "레드벨벳(Red Velvet)" },
  { song: "다시는 사랑하지 않고, 이별에 아파하기 싫어", artist: "백지영" },
  { song: "Square (2017)", artist: "백예린" },
  { song: "첫 겨울이니까", artist: "성시경, 아이유 (IU)" },
  { song: "십이월 이십오일의 고백", artist: "정승환" },
  {
    song: "아마두 (Feat. 우원재, 김효은, 넉살, Huckleberry P)",
    artist: "염따, 딥플로우, 팔로알토 (Paloalto), The Quiett, 사이먼 도미닉",
  },
  { song: "나의 오랜 연인에게", artist: "다비치" },
  { song: "헤어진 우리가 지켜야 할 것들", artist: "김나영, 양다일" },
  { song: "METEOR", artist: "창모 (CHANGMO)" },
  { song: "빌었어", artist: "창모 (CHANGMO)" },
  { song: "Obsession", artist: "EXO" },
  { song: "날 보러 와요 (Come See Me)", artist: "AOA" },
  { song: "Blueming", artist: "아이유 (IU)" },
  { song: "시간의 바깥", artist: "아이유 (IU)" },
  { song: "unlucky", artist: "아이유 (IU)" },
  { song: "그 사람", artist: "아이유 (IU)" },
  { song: "자장가", artist: "아이유 (IU)" },
  {
    song: "숨겨진 세상 (Into the Unknown End Credit Ver.) (겨울왕국 2)",
    artist: "태연 (TAEYEON)",
  },
  { song: "Into the Unknown", artist: "Idina Menzel, AURORA" },
  { song: "Show Yourself", artist: "Idina Menzel, Evan Rachel Wood" },
  { song: "HIP", artist: "마마무 (Mamamoo)" },
  { song: "이 번호로 전화해줘", artist: "바이브 (Vibe)" },
  {
    song: "차가워진 이 바람엔 우리가 써있어(Bad Love)",
    artist: "HYNN(박혜원)",
  },
  { song: "늦은 밤 너의 집 앞 골목길에서", artist: "노을" },
  { song: "5월의 밤", artist: "자이언티(Zion.T)" },
  { song: "Love poem", artist: "아이유 (IU)" },
  { song: "All I Want For Christmas Is You", artist: "Mariah Carey" },
  { song: "이별주", artist: "황인욱" },
  { song: "영화 속에 나오는 주인공처럼", artist: "펀치 (Punch)" },
  { song: "이별은 늘 그렇게 (Duet. 정은지)", artist: "허각" },
  { song: "불티 (Spark)", artist: "태연 (TAEYEON)" },
  { song: "인기 (Feat. 송가인, 챈슬러)", artist: "MC몽" },
  { song: "샤넬 (Feat. 박봄)", artist: "MC몽" },
  { song: "LION", artist: "(여자)아이들" },
  { song: "내 생애 가장 행복한 시간 Part.2 (Feat. 양다일)", artist: "MC몽" },
  { song: "떨어지는 낙엽까지도", artist: "헤이즈 (Heize)" },
  { song: "새 사랑", artist: "송하예" },
  { song: "있어줘요", artist: "장덕철" },
  { song: "허전해", artist: "폴킴" },
  { song: "이별행동", artist: "이우" },
  { song: "우리 어떻게 할까요", artist: "첸 (CHEN)" },
  { song: "천둥벌거숭이 (Feat. Jvcki Wai, 염따)", artist: "지코 (ZICO)" },
  { song: "사람", artist: "지코 (ZICO)" },
  {
    song: "어떻게 이별까지 사랑하겠어, 널 사랑하는 거지",
    artist: "악동뮤지션 (AKMU)",
  },
  { song: "달", artist: "악동뮤지션 (AKMU)" },
  { song: "조금 취했어 (Prod. 2soo)", artist: "임재현" },
  { song: "Feel Special", artist: "TWICE" },
  { song: "Memories", artist: "Maroon 5" },
  { song: "가끔 이러다", artist: "펀치 (Punch)" },
  { song: "워커홀릭", artist: "볼빨간사춘기" },
  { song: "XX", artist: "볼빨간사춘기" },
  { song: "25", artist: "볼빨간사춘기" },
  { song: "사랑이란 멜로는 없어", artist: "전상근" },
  { song: "가을밤 떠난 너", artist: "케이시 (Kassy)" },
  { song: "헤어지자 (Prod. 정키)", artist: "휘인" },
  { song: "다시 만날까 봐", artist: "V.O.S" },
  { song: "나빠(NAPPA)", artist: "크러쉬 (CRUSH)" },
  { song: "날라리 (LALALAY)", artist: "선미" },
  { song: "FLASH", artist: "X1 (엑스원)" },
  { song: "벗", artist: "닐로 (Nilo)" },
  {
    song: "담아 (Feat. 염따, pH-1) (Prod. BOYCOLD)",
    artist: "스윙스(Swings), Kid Milli, 매드 클라운",
  },
  { song: "흔들리는 꽃들 속에서 네 샴푸향이 느껴진거야", artist: "장범준" },
  { song: "음파음파 (Umpah Umpah)", artist: "레드벨벳(Red Velvet)" },
  { song: "Done For Me", artist: "펀치 (Punch)" },
  { song: "Say Goodbye", artist: "송하예" },
  { song: "안녕", artist: "폴킴" },
  { song: "내 목소리 들리니", artist: "벤 (Ben)" },
  { song: "방에 모기가 있어 (Do You Think Of Me?)", artist: "10cm" },
  { song: "BUNGEE (Fall in Love)", artist: "오마이걸 (OH MY GIRL)" },
  { song: "기억해줘요 내 모든 날과 그때를", artist: "거미" },
  { song: "그 끝에 그대", artist: "청하" },
  { song: "ICY", artist: "ITZY (있지)" },
  { song: "내 맘을 볼 수 있나요", artist: "헤이즈 (Heize)" },
  { song: "너만 너만 너만", artist: "양다일" },
  { song: "가라사대", artist: "비와이(BewhY)" },
  { song: "그대라는 시", artist: "태연 (TAEYEON)" },
  { song: "나의 어깨에 기대어요", artist: "10cm" },
  { song: "내 안부", artist: "이우" },
  { song: "Another Day", artist: "먼데이 키즈 (Monday Kiz), 펀치 (Punch)" },
  { song: "비오는 날 뭐해", artist: "하은 (라코스테남)" },
  { song: "헤어질 걸 알아", artist: "폴킴" },
  { song: "UN Village", artist: "백현 (BAEKHYUN)" },
  { song: "인사", artist: "멜로망스(MeloMance)" },
  {
    song: "We don`t talk together (Feat. 기리보이) (Prod. SUGA)",
    artist: "헤이즈 (Heize)",
  },
  { song: "U GOT IT", artist: "갓츄 (GOT U)" },
  { song: "헤어져줘서 고마워", artist: "벤 (Ben)" },
  { song: "비가 내리는 날에는", artist: "윤하" },
  { song: "괜찮아도 괜찮아 (That`s okay)", artist: "디오 (D.O.)" },
  { song: "열대야 (Fever)", artist: "여자친구 (GFRIEND)" },
  {
    song: "비워 (Beer) (Prod. Way Ched)",
    artist: "CHANGMO, Hash Swan, ASH ISLAND, 김효은, Leellamarz & The Quiett",
  },
  { song: "Uh-Oh", artist: "(여자)아이들" },
  { song: "Snapping", artist: "청하" },
  { song: "Senorita", artist: "Shawn Mendes, Camila Cabello" },
  { song: "포장마차", artist: "황인욱" },
  { song: "짐살라빔 (Zimzalabim)", artist: "레드벨벳(Red Velvet)" },
  { song: "술이 문제야", artist: "장혜진, 윤민수" },
  { song: "Honesty", artist: "Pink Sweat", artist: "" },
  { song: "서울 밤 (Feat. 빈지노)", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "BIRTHDAY", artist: "전소미" },
  {
    song: "아퍼 (Feat. Kid Milli, Lil tachi, 김승민, NO:EL, C JAMM)",
    artist: "기리보이(Giriboy)",
  },
  {
    song: "오늘도 빛나는 너에게 (To You My Light) (Feat.이라온)",
    artist: "마크툽 (Maktub)",
  },
  { song: "솔직하게 말해서 나", artist: "김나영" },
  { song: "BAND", artist: "창모, Hash Swan, ASH ISLAND, 김효은" },
  { song: "누구 없소 (NO ONE) (Feat. B.I of iKON)", artist: "이하이" },
  { song: "대충 입고 나와", artist: "우디(Woody)" },
  { song: "사랑이 식었다고 말해도 돼", artist: "먼데이 키즈 (Monday Kiz)" },
  { song: "Speechless (Full)", artist: "Naomi Scott" },
  { song: "A Whole New World", artist: "Mena Massoud, Naomi Scott" },
  { song: "Arabian Nights (2019)", artist: "Will Smith" },
  { song: "Prince Ali", artist: "Will Smith" },
  { song: "교통정리 (Feat. 헤이즈)", artist: "기리보이(Giriboy)" },
  { song: "안녕하세요", artist: "김재환" },
  { song: "너에게 못했던 내 마지막 말은", artist: "다비치" },
  { song: "비가 오잖아", artist: "소유 (SOYOU), 오반" },
  { song: "AH YEAH (아예)", artist: "WINNER" },
  { song: "오월의 어느 봄날 (Feat. 첸(CHEN))", artist: "임한별" },
  { song: "니 소식", artist: "송하예" },
  { song: "I Don`t Care", artist: "Ed Sheeran, Justin Bieber" },
  { song: "돈 Call Me (Prod. BRLLNT)", artist: "염따 (YumDDa)" },
  { song: "다섯 번째 계절 (SSFWL)", artist: "오마이걸 (OH MY GIRL)" },
  { song: "Goodbye", artist: "박효신" },
  { song: "If I Can`t Have You", artist: "Shawn Mendes" },
  { song: "이 밤", artist: "양다일" },
  { song: "FANCY", artist: "TWICE" },
  {
    song: "GO HIGH (Feat. 우원재, 창모 (CHANGMO), The Quiett) (Prod. CODE KUNST)",
    artist: "이영지",
  },
  {
    song: "작은 것들을 위한 시 (Boy With Luv) (Feat. Halsey)",
    artist: "방탄소년단",
  },
  { song: "소우주 (Mikrokosmos)", artist: "방탄소년단" },
  { song: "Make It Right", artist: "방탄소년단" },
  { song: "Dionysus", artist: "방탄소년단" },
  { song: "HOME", artist: "방탄소년단" },
  { song: "Jamais Vu", artist: "방탄소년단" },
  { song: "Intro : Persona", artist: "방탄소년단" },
  { song: "있어줄래", artist: "길구봉구" },
  { song: "Kill This Love", artist: "BLACKPINK" },
  { song: "Don`t Know What To Do", artist: "BLACKPINK" },
  { song: "나만, 봄", artist: "볼빨간사춘기" },
  { song: "별 보러 갈래?", artist: "볼빨간사춘기" },
  { song: "Mermaid", artist: "볼빨간사춘기" },
  { song: "나들이 갈까", artist: "볼빨간사춘기" },
  {
    song: "사월이 지나면 우리 헤어져요 (Beautiful goodbye)",
    artist: "첸 (CHEN)",
  },
  { song: "비올레타", artist: "IZ*ONE (아이즈원)" },
  { song: "시든 꽃에 물을 주듯", artist: "HYNN(박혜원)" },
  { song: "bad guy", artist: "Billie Eilish" },
  { song: "진심이 담긴 노래 (True Song)", artist: "케이시 (Kassy)" },
  { song: "사계 (Four Seasons)", artist: "태연 (TAEYEON)" },
  { song: "Blue", artist: "태연 (TAEYEON)" },
  { song: "On My Way", artist: "Alan Walker, Sabrina Carpenter, Farruko" },
  { song: "노래방에서", artist: "장범준" },
  { song: "당신과는 천천히", artist: "장범준" },
  { song: "일산으로", artist: "장범준" },
  { song: "SHE`S FINE", artist: "헤이즈 (Heize)" },
  { song: "그러니까 (Feat. Colde)", artist: "헤이즈 (Heize)" },
  { song: "그건 아마 우리의 잘못은 아닐 거야", artist: "백예린" },
  { song: "야간비행 (魔女の花)", artist: "백예린" },
  { song: "혼자", artist: "거미" },
  {
    song: "눈 (Prod. GIRIBOY)",
    artist: "강현준 (Lil tachi), 김호진 (HOTCHKISS)",
  },
  { song: "고고베베 (gogobebe)", artist: "마마무 (Mamamoo)" },
  { song: "주저하는 연인들을 위해", artist: "잔나비" },
  { song: "봄 (Feat. 산다라박)", artist: "박봄" },
  { song: "술이 달다 (Feat. 크러쉬)", artist: "에픽하이 (EPIK HIGH)" },
  { song: "호불호 (Feat. 기리보이) (Prod. By GRAY)", artist: "우원재" },
  { song: "오늘 밤에", artist: "홍진영" },
  { song: "그러나", artist: "10cm" },
  { song: "여자친구", artist: "하은요셉" },
  { song: "wish you were gay", artist: "Billie Eilish" },
  { song: "누아르 (Noir)", artist: "선미" },
  { song: "Sucker", artist: "Jonas Brothers" },
  { song: "사랑해서 그래", artist: "강민경" },
  { song: "Senorita", artist: "(여자)아이들" },
  { song: "미운 날 (The day, I hate myself)", artist: "닐로 (Nilo)" },
  { song: "멍청이(twit)", artist: "화사(Hwa Sa)" },
  { song: "달라달라", artist: "ITZY (있지)" },
  { song: "Talk", artist: "Khalid, Disclosure" },
  { song: "오랜만이야 (Feat. Zion.T)", artist: "로꼬 (LOCO)" },
  { song: "i`m so tired...", artist: "Lauv, Troye Sivan" },
  { song: "이 노래가 클럽에서 나온다면", artist: "우디(Woody)" },
  { song: "Heu ! (Full Ver.)", artist: "수퍼비" },
  { song: "신청곡 (Feat. SUGA of BTS)", artist: "이소라" },
  { song: "Home", artist: "세븐틴" },
  { song: "7 rings", artist: "Ariana Grande" },
  { song: "초록빛", artist: "폴킴" },
  { song: "해야 (Sunrise)", artist: "여자친구 (GFRIEND)" },
  {
    song: "띵 (Prod. By 기리보이)",
    artist: "Jvcki Wai, Young B, Osshun Gum, 한요한",
  },
  { song: "Dancing With A Stranger", artist: "Sam Smith, Normani" },
  { song: "길 (Song by 아이유, 헨리, 조현아, 양다일)", artist: "god" },
  { song: "song: song: (응응)", artist: "에이핑크 (Apink)" },
  { song: "넘쳐흘러", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "벌써 12시", artist: "청하" },
  { song: "옥탑방", artist: "엔플라잉 (N.Flying)" },
  { song: "사계 (하루살이)", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "습관 (Bad Habits)", artist: "숀 (SHAUN)" },
  { song: "그때가 좋았어", artist: "케이시 (Kassy)" },
  { song: "알았다면", artist: "장덕철" },
  { song: "MILLIONS", artist: "WINNER" },
  { song: "사랑 알 수 없나봐", artist: "폴킴" },
  { song: "첫눈에", artist: "헤이즈 (Heize)" },
  {
    song: "Sunflower (Spider-Man : Into The Spider-Verse)",
    artist: "Post Malone & Swae Lee",
  },
  { song: "Love Shot", artist: "EXO" },
  { song: "We all lie", artist: "하진" },
  { song: "180도", artist: "벤 (Ben)" },
  { song: "동화 (Feat. 아이유)", artist: "김동률" },
  { song: "행복", artist: "오반 (OVAN)" },
  { song: "RBB (Really Bad Boy)", artist: "레드벨벳(Red Velvet)" },
  { song: "너도 그냥 날 놓아주면 돼", artist: "윤건" },
  { song: "Wind flower", artist: "마마무 (Mamamoo)" },
  { song: "흔한 이별", artist: "허각" },
  { song: "첫눈처럼 너에게 가겠다 (Prod. 로코베리)", artist: "김범수" },
  { song: "아낙네", artist: "송민호" },
  { song: "come out and play", artist: "Billie Eilish" },
  { song: "알러뷰", artist: "EXID" },
  { song: "그대가 내 안에 박혔다", artist: "황치열" },
  { song: "봄바람", artist: "Wanna One (워너원)" },
  { song: "SOLO", artist: "제니 (JENNIE)" },
  { song: "아름답고도 아프구나", artist: "비투비 (BTOB)" },
  { song: "북향 (Feat. 오혁)", artist: "다이나믹 듀오 (Dynamic Duo)" },
  { song: "소년점프 (Feat. 배기성)", artist: "마미손" },
  { song: "신용재", artist: "하은 (라코스테남)" },
  { song: "Goodbye", artist: "웬디" },
  { song: "YES or YES", artist: "TWICE" },
  { song: "너는 어땠을까", artist: "노을" },
  { song: "thank u, next", artist: "Ariana Grande" },
  { song: "POP/STARS", artist: "(여자)아이들, Madison Beer, Jaira Burns" },
  { song: "수퍼비와 (Feat. BewhY) (Prod. BewhY)", artist: "SUPERBEE" },
  {
    song: "NoNo (Feat. 사이먼 도미닉) (Prod. 코드 쿤스트)",
    artist: "루피(Loopy)",
  },
  { song: "Tempo", artist: "EXO" },
  { song: "Gravity", artist: "EXO" },
  { song: "닿은 순간 (Ooh La La La)", artist: "EXO" },
  { song: "44036", artist: "EXO" },
  { song: "Sign", artist: "EXO" },
  { song: "여기 있을게 (Smile On My Face)", artist: "EXO" },
  { song: "너를 만나", artist: "폴킴" },
  { song: "라비앙로즈 (La Vie en Rose)", artist: "IZ*ONE (아이즈원)" },
  { song: "Waste It On Me (Feat. BTS (방탄소년단))", artist: "Steve Aoki" },
  { song: "내 생에 아름다운", artist: "케이윌 (K.Will)" },
  { song: "Friend", artist: "비투비 (BTOB)" },
  { song: "Save (Feat. 팔로알토) (Prod. 코드 쿤스트)", artist: "루피(Loopy)" },
  { song: "Bohemian Rhapsody", artist: "Queen" },
  { song: "Kiss And Make Up", artist: "Dua Lipa, BLACKPINK" },
  { song: "친구로 지내자면서 (Prod. By 전태익)", artist: "황인욱" },
  { song: "꿈처럼 내린", artist: "다비치" },
  { song: "벚꽃연가", artist: "첸 (CHEN)" },
  { song: "고백", artist: "양다일" },
  {
    song: "멋지게 인사하는 법 (Feat. 슬기 of Red Velvet)",
    artist: "자이언티(Zion.T)",
  },
  { song: "Hate You (Feat. 우원재) (Prod. 코드 쿤스트)", artist: "pH-1" },
  { song: "너에게", artist: "김민석" },
  { song: "삐삐", artist: "아이유 (IU)" },
  { song: "Paris In The Rain", artist: "Lauv" },
  { song: "시간이 들겠지 (Feat. Colde)", artist: "로꼬 (LOCO)" },
  { song: "I Like Me Better", artist: "Lauv" },
  {
    song: "Good Day (Feat. 팔로알토) (Prod. 코드 쿤스트)",
    artist: "pH-1, Kid Milli, 루피 (Loopy)",
  },
  { song: "사임사임 (Feat. CHANGMO)", artist: "Coogie, SUPERBEE, D.Ark" },
  { song: "Shallow", artist: "Lady Gaga, Bradley Cooper" },
  { song: "Without Me", artist: "Halsey" },
  { song: "이별길 (GOODBYE ROAD)", artist: "iKON" },
  { song: "나", artist: "박원" },
  { song: "구름", artist: "로시 (Rothy)" },
  { song: "comethru", artist: "Jeremy Zucker" },
  { song: "사랑에 연습이 있었다면 (Prod. 2soo)", artist: "임재현" },
  { song: "동화", artist: "멜로망스(MeloMance)" },
  { song: "Better Now", artist: "Post Malone" },
  { song: "2002", artist: "Anne-Marie" },
  { song: "Day 1 ◑", artist: "HONNE" },
  { song: "In My Blood", artist: "Shawn Mendes" },
  { song: "Done For Me", artist: "Charlie Puth, Kehlani" },
  { song: "Psycho (Feat. Ty Dolla", artist: "ign)", artist: "Post Malone" },
  { song: "Lullaby", artist: "Sigala, Paloma Faith" },
  { song: "Never Enough", artist: "Loren Allred" },
  { song: "Martini Blue", artist: "DPR LIVE" },
  { song: "Lip & Hip", artist: "현아 (HyunA)" },
  { song: "갈 수가 없어", artist: "벤 (Ben)" },
  { song: "Rewrite The Stars", artist: "Zac Efron, Zendaya" },
  { song: "뻔한 이별", artist: "소유, 성시경" },
  { song: "Twilight", artist: "Wanna One (워너원)" },
  { song: "Snowman", artist: "Sia" },
  { song: "러브스토리 (Feat. 크러쉬)", artist: "수란 (SURAN)" },
  { song: "박수", artist: "세븐틴" },
  { song: "Too Good At Goodbyes", artist: "Sam Smith" },
  { song: "Palace", artist: "Sam Smith" },
  {
    song: "All Falls Down (Feat. Noah Cyrus, Digital Farm Animals)",
    artist: "Alan Walker",
  },
  { song: "This Is Me", artist: "Keala Settle, The Greatest Showman Ensemble" },
  { song: "빈차 (Feat. 오혁)", artist: "에픽하이 (EPIK HIGH)" },
  { song: "헤어질 수 밖에", artist: "김나영" },
  { song: "가을 안부", artist: "먼데이 키즈 (Monday Kiz)" },
  { song: "너를 찾아서", artist: "윤종신" },
  {
    song: "Perhaps Love (사랑인가요) (Prod. by 박근태)",
    artist: "에릭남, 치즈 (CHEEZE)",
  },
  { song: "썸 탈꺼야", artist: "볼빨간사춘기" },
  { song: "나의 사춘기에게", artist: "볼빨간사춘기" },
  { song: "Blue", artist: "볼빨간사춘기" },
  { song: "고쳐주세요", artist: "볼빨간사춘기" },
  { song: "상상", artist: "볼빨간사춘기" },
  { song: "길", artist: "폴킴" },
  { song: "잠 못 드는 밤 비는 내리고", artist: "아이유 (IU)" },
  { song: "비밀의 화원", artist: "아이유 (IU)" },
  { song: "매일 그대와", artist: "아이유 (IU)" },
  { song: "특별해", artist: "젝스키스" },
  { song: "The Spectre", artist: "Alan Walker" },
  { song: "She (Hidden Track No.V 1월 선정곡)", artist: "잔나비" },
  { song: "베베 (BABE)", artist: "현아 (HyunA)" },
  { song: "Red Sun (Feat. ZICO, Swings)", artist: "행주" },
  { song: "Look What You Made Me Do", artist: "Taylor Swift" },
  { song: "활활 (Burn It Up)", artist: "Wanna One (워너원)" },
  {
    song: "N분의 1 (Feat. 다이나믹듀오)",
    artist: "넉살, 한해, 조우찬, 라이노",
  },
  {
    song: "요즘것들 (Feat. ZICO & DEAN)",
    artist: "행주, 양홍원 (Young B), Hash Swan, 킬라그램(Killagramz)",
  },
  { song: "LOVE ME LOVE ME", artist: "WINNER" },
  { song: "ISLAND", artist: "WINNER" },
  { song: "Holiday", artist: "소녀시대" },
  { song: "귀를 기울이면 (LOVE WHISPER)", artist: "여자친구 (GFRIEND)" },
  { song: "있다면", artist: "뉴이스트 W" },
  { song: "있잖아", artist: "폴킴" },
  { song: "Sriracha", artist: "Marteen" },
  { song: "DINOSAUR", artist: "악동뮤지션 (AKMU)" },
  { song: "Artist", artist: "지코 (ZICO)" },
  { song: "FANXY CHILD (Feat. FANXY CHILD)", artist: "지코 (ZICO)" },
  { song: "Sorry Not Sorry", artist: "Demi Lovato" },
  { song: "아침에 (Feat. Bryn)", artist: "양홍원 (Young B)" },
  { song: "FIVE", artist: "에이핑크 (Apink)" },
  { song: "나로 말할 것 같으면 (Yes I am)", artist: "마마무 (Mamamoo)" },
  {
    song: "Feels (Feat. Pharrell Williams, Katy Perry & Big Sean)",
    artist: "Calvin Harris",
  },
  { song: "Why Don`t You Know (Feat. 넉살)", artist: "청하" },
  { song: "NEVER", artist: "국민의 아들" },
  { song: "Oh Little Girl", artist: "슬레이트" },
  { song: "New Rules", artist: "Dua Lipa" },
  { song: "IDGAF", artist: "Dua Lipa" },
  { song: "LONELY", artist: "씨스타 (Sistar)" },
  { song: "CALLING YOU", artist: "하이라이트(Highlight)" },
  { song: "사랑앓이 (With 김나영)", artist: "FTISLAND (FT 아일랜드)" },
  { song: "There For You", artist: "Martin Garrix, Troye Sivan" },
  { song: "지나쳐 (FEAT. DEAN)", artist: "로꼬 (LOCO)" },
  { song: "울고 싶지 않아", artist: "세븐틴" },
  { song: "혼자", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "처음부터 너와 나", artist: "볼빨간사춘기" },
  { song: "SIGNAL", artist: "TWICE" },
  { song: "맞지?", artist: "언니쓰" },
  { song: "New Face", artist: "싸이 (PSY)" },
  { song: "I LUV IT", artist: "싸이 (PSY)" },
  { song: "미치고 싶다", artist: "한동근" },
  {
    song: "I`m The One (Feat. Justin Bieber, Quavo, Chance the Rapper, Lil Wayne)",
    artist: "DJ Khaled",
  },
  { song: "아프지 마요", artist: "젝스키스" },
  { song: "TOMBOY", artist: "혁오 (hyukoh)" },
  { song: "이름에게", artist: "아이유 (IU)" },
  { song: "이런 엔딩", artist: "아이유 (IU)" },
  { song: "이 지금", artist: "아이유 (IU)" },
  { song: "잼잼", artist: "아이유 (IU)" },
  { song: "Shape Of You", artist: "제이플라 (J.Fla)" },
  {
    song: "Despacito (Remix)",
    artist: "Luis Fonsi, Justin Bieber, Daddy Yankee",
  },
  { song: "BLUE MOON (Prod. GroovyRoom)", artist: "효린, 창모" },
  { song: "She`s a Baby", artist: "지코 (ZICO)" },
  { song: "너란 봄 (Feat. 하림)", artist: "정은지" },
  { song: "사랑이 잘 (With 오혁)", artist: "아이유 (IU)" },
  { song: "Make Me Love You", artist: "태연 (TAEYEON)" },
  { song: "REALLY REALLY", artist: "WINNER" },
  { song: "HUMBLE.", artist: "Kendrick Lamar" },
  { song: "I`ll be yours", artist: "걸스데이 (Girl`s Day)" },
  { song: "얼굴 찌푸리지 말아요", artist: "하이라이트(Highlight)" },
  { song: "Symphony (Feat. Zara Larsson)", artist: "Clean Bandit" },
  { song: "나야 나 (PICK ME)", artist: "PRODUCE 101" },
  { song: "부담이 돼 (Feat. 휘인 of 마마무)", artist: "정키 (Jung Key)" },
  { song: "MOVIE", artist: "비투비 (BTOB)" },
  { song: "FINGERTIP", artist: "여자친구 (GFRIEND)" },
  { song: "Perfect", artist: "Ed Sheeran" },
  { song: "Galway Girl", artist: "Ed Sheeran" },
  { song: "Slide (Feat. Frank Ocean & Migos)", artist: "Calvin Harris" },
  { song: "Fine", artist: "태연 (TAEYEON)" },
  { song: "오늘도 그대만 (Feat. 정동원)", artist: "타디스 프로젝트" },
  { song: "Bellyache", artist: "Billie Eilish" },
  { song: "KNOCK KNOCK", artist: "TWICE" },
  { song: "니가 보고싶은 밤", artist: "윤딴딴" },
  { song: "좋아해 (bye)", artist: "CHEEZE" },
  { song: "넘어와 (Feat. 백예린)", artist: "DEAN" },
  { song: "비가와 (Rain)", artist: "소유, 백현 (BAEKHYUN)" },
  { song: "Not Today", artist: "방탄소년단" },
  { song: "YESTERDAY", artist: "블락비 (Block B)" },
  {
    song: "우리집을 못 찾겠군요 (Feat. 볼빨간사춘기)",
    artist: "매드 클라운 (Mad Clown)",
  },
  {
    song: "Beauty and the Beast (영화 미녀와 야수 삽입곡 (Beauty and the Beast OST))",
    artist: "Ariana Grande, John Legend",
  },
  { song: "Rookie", artist: "레드벨벳(Red Velvet)" },
  { song: "노래", artist: "자이언티(Zion.T)" },
  { song: "Complex (Feat. G-DRAGON)", artist: "자이언티(Zion.T)" },
  { song: "미안해 (Feat. Beenzino)", artist: "자이언티(Zion.T)" },
  { song: "기다렸다 가", artist: "다이나믹 듀오 (Dynamic Duo) & 첸 (CHEN)" },
  { song: "Round and round (Feat. 한수지)", artist: "헤이즈 (Heize)" },
  { song: "행복한 척", artist: "수지" },
  { song: "Paris", artist: "The Chainsmokers" },
  { song: "Despacito (Feat. Daddy Yankee)", artist: "Luis Fonsi" },
  { song: "소원", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "오랜 날 오랜 밤", artist: "악동뮤지션 (AKMU)" },
  { song: "Excuse Me", artist: "AOA" },
  { song: "I Miss You", artist: "소유 (SOYOU)" },
  { song: "당신의 밤 (Feat. 오혁)", artist: "황광희 X 개코" },
  { song: "쏘아", artist: "하하 X MINO" },
  { song: "Who are you", artist: "샘김" },
  { song: "이쁘다니까", artist: "에디킴" },
  { song: "좋다고 말해", artist: "볼빨간사춘기" },
  { song: "Beautiful", artist: "크러쉬 (CRUSH)" },
  { song: "에라 모르겠다", artist: "빅뱅" },
  { song: "LAST DANCE", artist: "빅뱅" },
  { song: "GIRLFRIEND", artist: "빅뱅" },
  { song: "Hush", artist: "Lasse Lindh" },
  { song: "내 눈에만 보여", artist: "10cm" },
  {
    song: "City Of Stars (From `La La Land` Soundtrack)",
    artist: "Ryan Gosling & Emma Stone",
  },
  {
    song: "Another Day Of Sun (From `La La Land` Soundtrack)",
    artist: "La La Land Cast",
  },
  {
    song: "A Lovely Night (From `La La Land` Soundtrack)",
    artist: "Ryan Gosling & Emma Stone",
  },
  { song: "저 별", artist: "헤이즈 (Heize)" },
  { song: "Stay With Me", artist: "찬열 (CHANYEOL), 펀치 (Punch)" },
  { song: "Alone", artist: "Alan Walker" },
  { song: "이 바보야", artist: "정승환" },
  { song: "BERMUDA TRIANGLE (Feat. Crush, DEAN)", artist: "지코 (ZICO)" },
  { song: "I Feel It Coming (Feat. Daft Punk)", artist: "The Weeknd" },
  { song: "꽃길 (Prod. By ZICO)", artist: "세정" },
  { song: "That`s What I Like", artist: "Bruno Mars" },
  { song: "Decalcomanie (데칼코마니)", artist: "마마무 (Mamamoo)" },
  { song: "남아있어 (Feat. Crush)", artist: "로꼬 (LOCO)" },
  { song: "널 너무 사랑해서 (Feat. 정은지 of 에이핑크)", artist: "MC몽" },
  { song: "18991231", artist: "태연 (TAEYEON)" },
  { song: "TT", artist: "TWICE" },
  { song: "Rockabye (Feat. Sean Paul & Anne-Marie)", artist: "Clean Bandit" },
  { song: "All I Wanna Do (K) (Feat. Hoody, Loco)", artist: "박재범" },
  { song: "너무너무너무", artist: "아이오아이 (I.O.I)" },
  { song: "어떻게 지내", artist: "크러쉬 (CRUSH)" },
  { song: "Don`t Wanna Know (Feat. Kendrick Lamar)", artist: "Maroon 5" },
  { song: "내 옆에 그대인 걸", artist: "다비치" },
  { song: "빌려줄게", artist: "신용재" },
  { song: "세 단어", artist: "젝스키스" },
  { song: "숨", artist: "박효신" },
  { song: "끝", artist: "권진아" },
  { song: "Dancing King", artist: "유재석, EXO" },
  { song: "다정하게, 안녕히", artist: "성시경" },
  { song: "The Greatest (Feat. Kendrick Lamar)", artist: "Sia" },
  { song: "러시안 룰렛 (Russian Roulette)", artist: "레드벨벳(Red Velvet)" },
  { song: "구르미 그린 달빛", artist: "거미" },
  { song: "우주를 줄게", artist: "볼빨간사춘기" },
  { song: "나만 안되는 연애", artist: "볼빨간사춘기" },
  { song: "You(=I)", artist: "볼빨간사춘기" },
  { song: "심술", artist: "볼빨간사춘기" },
  { song: "프리지아", artist: "볼빨간사춘기" },
  { song: "Blow Your Mind (Mwah)", artist: "Dua Lipa" },
  { song: "목요일 밤 (Feat. 빈지노)", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "너를 위해", artist: "첸, 백현, 시우민 (EXO)" },
  { song: "If You", artist: "에일리 (Ailee)" },
  { song: "잠은 다 잤나봐요", artist: "소유, 유승우" },
  { song: "Lotto", artist: "EXO" },
  { song: "puzzle", artist: "씨잼 (C Jamm), 비와이(BewhY)" },
  { song: "휘파람", artist: "BLACKPINK" },
  { song: "붐바야", artist: "BLACKPINK" },
  { song: "Let Me Love You (Feat. Justin Bieber)", artist: "DJ Snake" },
  { song: "뜨거운 여름밤은 가고 남은 건 볼품없지만", artist: "잔나비" },
  { song: "사랑해요", artist: "김범수" },
  { song: "여름밤에 우린", artist: "스탠딩 에그(Standing Egg)" },
  { song: "Cold Water (Feat. Justin Bieber & MO)", artist: "Major Lazer" },
  { song: "Warm On A Cold Night", artist: "HONNE" },
  { song: "아름다워", artist: "창모 (CHANGMO)" },
  { song: "마에스트로 (Maestro)", artist: "창모 (CHANGMO)" },
  { song: "And July (Feat. DEAN, DJ Friz)", artist: "헤이즈 (Heize)" },
  { song: "The Ocean (Feat. Shy Martin) (Radio Edit)", artist: "Mike Perry" },
  { song: "네 생각", artist: "존 박" },
  { song: "너 그리고 나 (NAVILLERA)", artist: "여자친구 (GFRIEND)" },
  { song: "Day Day (Feat. 박재범) (Prod. by GRAY)", artist: "비와이(BewhY)" },
  { song: "Why So Lonely", artist: "원더걸스 (Wonder girls)" },
  { song: "아주 NICE", artist: "세븐틴" },
  { song: "Forever (Prod. by GRAY)", artist: "비와이(BewhY)" },
  { song: "호랑나비 (Feat. Gill, 리듬파워)", artist: "보이비 (Boi B)" },
  { song: "Shut Up (Feat. 유희열)", artist: "언니쓰" },
  { song: "Why", artist: "태연 (TAEYEON)" },
  {
    song: "맘 편히 (Comfortable)",
    artist: "사이먼 도미닉 (Simon Dominic), GRAY, 원 (ONE)",
  },
  { song: "I Like That", artist: "씨스타 (Sistar)" },
  { song: "Bye bye my blue", artist: "백예린" },
  {
    song: "니가 알던 내가 아냐 (Prod. by GRAY)",
    artist: "사이먼 도미닉 (Simon Dominic), 원(ONE), 지투(G2), BewhY",
  },
  { song: "Monster", artist: "EXO" },
  { song: "Lucky One", artist: "EXO" },
  { song: "Treat You Better", artist: "Shawn Mendes" },
  { song: "쏘쏘", artist: "백아연" },
  { song: "오늘", artist: "O.WHEN(오왠)" },
  { song: "Side To Side (Feat. Nicki Minaj)", artist: "Ariana Grande" },
  { song: "사랑이 뭔데", artist: "서현진, 유승우" },
  { song: "Good Luck", artist: "AOA" },
  { song: "CAN`T STOP THE FEELING!", artist: "Justin Timberlake" },
  { song: "꿈처럼", artist: "벤 (Ben)" },
  { song: "우아해 (woo ah)", artist: "크러쉬 (CRUSH)" },
  {
    song: "This Is What You Came For (Feat. Rihanna)",
    artist: "Calvin Harris",
  },
  { song: "RE-BYE", artist: "악동뮤지션 (AKMU)" },
  { song: "불타오르네 (FIRE)", artist: "방탄소년단" },
  { song: "Save ME", artist: "방탄소년단" },
  { song: "How To Love (Feat. Sofia Reyes)", artist: "Cash Cash" },
  { song: "내 입술 따뜻한 커피처럼 (Feat. 이성경)", artist: "에디킴" },
  { song: "CHEER UP", artist: "TWICE" },
  { song: "하늘바라기 (feat. 하림)", artist: "정은지" },
  { song: "돌아오지마 (Feat. 용준형 of 비스트)", artist: "헤이즈 (Heize)" },
  { song: "How Can I Love You", artist: "XIA(준수)" },
  { song: "Toy", artist: "블락비 (Block B)" },
  { song: "그대, 바람이 되어", artist: "엠씨더맥스 (M.C The Max)" },
  { song: "7 Years", artist: "Lukas Graham" },
  { song: "사랑하자", artist: "SG 워너비" },
  { song: "꿈속에 너 (Feat. 전상근)", artist: "에이치코드 (H:CODE)" },
  {
    song: "i hate u, i love u (Feat. olivia o`brien) (album ver.)",
    artist: "gnash",
  },
  { song: "사랑에 빠졌죠 (당신만이)", artist: "장범준" },
  { song: "D (half moon) (Feat. 개코)", artist: "DEAN" },
  { song: "21", artist: "DEAN" },
  { song: "같은 곳에서", artist: "소녀온탑" },
  { song: "말해! 뭐해?", artist: "케이윌 (K.Will)" },
  { song: "다시 너를", artist: "매드 클라운 (Mad Clown), 김나영" },
  { song: "Don`t Cry (우리동네 음악대장)", artist: "우리 동네 음악대장" },
  { song: "You Are My Everything", artist: "거미" },
  { song: "봄인가 봐 (Spring Love)", artist: "에릭남, 웬디" },
  { song: "이 사랑", artist: "다비치" },
  { song: "넌 is 뭔들", artist: "마마무 (Mamamoo)" },
  { song: "Everytime", artist: "첸(CHEN), 펀치 (Punch)" },
  { song: "공감 (Feat. 서영은)", artist: "정준영" },
  { song: "ALWAYS", artist: "윤미래 (T)" },
  { song: "Don`t Let Me Down (Feat. Daya)", artist: "The Chainsmokers" },
  { song: "Rain", artist: "태연 (TAEYEON)" },
  { song: "센치해", artist: "WINNER" },
  {
    song: "We Don`t Talk Anymore (Feat. Selena Gomez)",
    artist: "Charlie Puth",
  },
  { song: "Left Right Left", artist: "Charlie Puth" },
  { song: "Up All Night", artist: "Charlie Puth" },
  { song: "Marvin Gaye (Feat. Meghan Trainor)", artist: "Charlie Puth" },
  { song: "I Miss You", artist: "마마무 (Mamamoo)" },
  { song: "what2do (Feat. Crush, Jeff Bernat)", artist: "DEAN" },
  { song: "시간을 달려서 (Rough)", artist: "여자친구 (GFRIEND)" },
  { song: "너는 나 나는 너", artist: "지코 (ZICO)" },
  { song: "사랑이었다 (Feat. 루나 of f(x))", artist: "지코 (ZICO)" },
  { song: "For Him. (Feat. Allday)", artist: "Troye Sivan" },
  { song: "잊어버리지마 (Feat.태연)", artist: "크러쉬 (CRUSH)" },
  { song: "Faded", artist: "Alan Walker" },
  { song: "Dream", artist: "수지, 백현 (BAEKHYUN)" },
  { song: "니가 하면 로맨스 (feat.다비치)", artist: "케이윌 (K.Will)" },
  { song: "또 하루 (Feat. 개코)", artist: "Gary (개리)" },
  { song: "어땠을까", artist: "김나영" },
  { song: "함께", artist: "노을" },
  { song: "PICK ME", artist: "PRODUCE 101" },
  { song: "사랑이 맞을거야", artist: "윤미래 (T)" },
  { song: "유레카 (Feat. Zion.T)", artist: "지코 (ZICO)" },
  { song: "네게 줄 수 있는건 오직 사랑뿐", artist: "디셈버 (December)" },
  { song: "Everglow", artist: "Coldplay" },
  { song: "DADDY (Feat. CL of 2NE1)", artist: "싸이 (Psy)" },
  { song: "나팔바지", artist: "싸이 (Psy)" },
  { song: "우주를 건너", artist: "백예린" },
  { song: "혜화동 (혹은 쌍문동)", artist: "박보람" },
  { song: "소녀", artist: "오혁" },
  { song: "When We Were Young", artist: "Adele" },
  {
    song: "못먹는 감 (Sour Grapes)",
    artist: "산이(San E), 매드 클라운(Mad Clown)",
  },
  { song: "HOT PINK", artist: "EXID" },
  { song: "Boys And Girls (Feat. Babylon)", artist: "지코 (ZICO)" },
  { song: "청춘 (Feat. 김창완)", artist: "김필" },
  { song: "4 Walls", artist: "f(x)" },
  { song: "냉탕에 상어 (Feat. 블랙넛)", artist: "슈퍼비" },
  { song: "Sorry", artist: "Justin Bieber" },
  { song: "Hello", artist: "Adele" },
  { song: "스물셋", artist: "아이유 (IU)" },
  { song: "무릎", artist: "아이유 (IU)" },
  { song: "푸르던", artist: "아이유 (IU)" },
  { song: "OOH-AHH하게", artist: "TWICE" },
  { song: "모르나봐", artist: "소유, 브라더수" },
  { song: "No Make Up", artist: "자이언티(Zion.T)" },
  { song: "I (Feat. 버벌진트)", artist: "태연 (TAEYEON)" },
  { song: "Ah-Choo", artist: "러블리즈" },
  { song: "리듬 타 (RHYTHM TA)", artist: "iKON" },
  { song: "가끔", artist: "지아 (Zia)" },
  { song: "또 다시 사랑", artist: "임창정" },
  { song: "어깨", artist: "소유, 권정열" },
  { song: "바람이나 좀 쐐 (Feat. MIWOO)", artist: "Gary (개리)" },
  { song: "보통연애 (Feat. 박보람)", artist: "박경" },
  { song: "하루의 끝 (End of a day)", artist: "종현 (JONGHYUN)" },
  { song: "취향저격", artist: "iKON" },
  { song: "Dumb Dumb", artist: "레드벨벳(Red Velvet)" },
  { song: "FOOLS", artist: "Troye Sivan" },
  { song: "Okey Dokey", artist: "송민호, 지코(ZICO)" },
  { song: "What Do You Mean?", artist: "Justin Bieber" },
  { song: "One Call Away", artist: "Charlie Puth" },
  { song: "겁 (Feat. 태양)", artist: "송민호" },
  { song: "레옹", artist: "이유 갓지(GOD G)않은이유(박명수, 아이유)" },
  { song: "맙소사", artist: "황태지(황광희, 태양, 지드래곤)" },
  { song: "스폰서", artist: "으뜨거따시(하하, 자이언티)" },
  { song: "멋진헛간", artist: "오대천왕(정형돈, 밴드 혁오)" },
  { song: "I`m So Sexy", artist: "댄싱게놈(유재석, JYP)" },
  { song: "가슴 뛰도록", artist: "SG워너비" },
  { song: "Lion Heart", artist: "소녀시대" },
  { song: "오빠차", artist: "인크레더블, 타블로, 지누션" },
  { song: "사이먼 도미닉", artist: "사이먼 도미닉 (Simon Dominic)" },
  { song: "우리 사랑하지 말아요", artist: "빅뱅" },
  { song: "쩔어 (GD&T.O.P)", artist: "빅뱅" },
  { song: "I Feel You", artist: "원더걸스 (Wonder Girls)" },
  {
    song: "거북선 (Feat. 팔로알토)",
    artist: "자메즈 (Ja Mezz), 앤덥(Andup), 송민호",
  },
  { song: "I`m Not Sorry (Feat. Eric Bellinger)", artist: "DEAN" },
  { song: "오늘부터 우리는 (Me gustas tu)", artist: "여자친구 (GFRIEND)" },
  { song: "New Thang", artist: "Redfoo (LMFAO)" },
  { song: "Remember", artist: "에이핑크 (Apink)" },
  { song: "Oasis (Feat. ZICO)", artist: "크러쉬 (CRUSH)" },
  { song: "PARTY", artist: "소녀시대" },
  { song: "링마벨 (Ring My Bell)", artist: "걸스데이 (Girl`s Day)" },
  {
    song: "사랑할수록 (화생방실 클레오파트라)",
    artist: "화생방실 클레오파트라",
  },
  { song: "IF YOU", artist: "빅뱅" },
  { song: "맨정신", artist: "빅뱅" },
  { song: "심쿵해 (Heart Attack)", artist: "AOA" },
  { song: "SHAKE IT", artist: "씨스타 (Sistar)" },
  { song: "음오아예 (Um Oh Ah Yeh)", artist: "마마무 (Mamamoo)" },
  { song: "아프다", artist: "지코 (ZICO), 소진" },
  { song: "LOVE ME RIGHT", artist: "EXO" },
  { song: "뱅뱅뱅 (BANG BANG BANG)", artist: "빅뱅" },
  { song: "WE LIKE 2 PARTY", artist: "빅뱅" },
  { song: "와리가리", artist: "혁오 (hyukoh)" },
  { song: "사랑의 시작은 고백에서부터", artist: "김범수" },
  { song: "몸매 (MOMMAE) (Feat. Ugly Duck)", artist: "박재범" },
  { song: "이럴거면 그러지말지 (Feat. 영현)", artist: "백아연" },
  { song: "꺼내 먹어요", artist: "자이언티(Zion.T)" },
  { song: "마음", artist: "아이유 (IU)" },
  { song: "View", artist: "샤이니 (SHINee)" },
  { song: "Madeleine Love", artist: "CHEEZE" },
  { song: "Flashlight", artist: "Jessie J" },
  { song: "LOSER", artist: "빅뱅" },
  { song: "BAE BAE", artist: "빅뱅" },
  { song: "I NEED U", artist: "방탄소년단" },
  { song: "그 남잔 말야", artist: "엠씨 더 맥스(M.C the Max)" },
  { song: "Me You (Feat. 백예린 of 15&)", artist: "산이 (San E)" },
  { song: "연예할래", artist: "박보람" },
  { song: "한번 더 말해줘 (Feat. 장한나)", artist: "지누션" },
  { song: "품행제로", artist: "블락비 바스타즈" },
  { song: "아예 (Ah Yeah)", artist: "EXID" },
  { song: "어머님이 누구니 (Feat. 제시)", artist: "박진영" },
  { song: "우연히 봄", artist: "로꼬 (LOCO), 유주 (여자친구)" },
  { song: "다른 남자 말고 너", artist: "miss A" },
  { song: "CALL ME BABY", artist: "EXO" },
  { song: "아무도 모르게 (Prod. by MC몽)", artist: "치타, 에일리" },
  { song: "꽃이 핀다", artist: "케이윌 (K.will)" },
  { song: "새벽 가로수길 (With 송유빈)", artist: "백지영" },
  { song: "Puss (Prod.by 라이머)", artist: "지민, 아이언" },
  { song: "두사랑 (Feat. 매드클라운)", artist: "다비치" },
  {
    song: "See You Again (폴 워커 추모 엔딩곡)",
    artist: "Charlie Puth, Wiz Khalifa",
  },
  { song: "Ice Cream Cake", artist: "레드벨벳(Red Velvet)" },
  { song: "사월의 눈", artist: "허각" },
  { song: "Apple (Feat. 박재범)", artist: "가인" },
  { song: "The Time Goes On", artist: "비와이 (BewhY)" },
  { song: "우린 알아", artist: "양다일, 정키 (JungKey)" },
  { song: "사랑 범벅 (Feat. 챈슬러 of the channels)", artist: "MC몽" },
  { song: "시작이 좋아 2015 (Prod. By 버벌진트)", artist: "지민, 슬옹" },
  { song: "오빠야", artist: "신현희와김루트" },
  { song: "Samsara (Feat. Emila)", artist: "Tungevaag, Raaban" },
  { song: "My Type (Prod. by 버벌진트)", artist: "제시(Jessi), 치타, 강남" },
  { song: "Love Me Like You Do", artist: "Ellie Goulding" },
  { song: "미쳐", artist: "포미닛 (4minute)" },
  { song: "같은 시간 속의 너", artist: "나얼" },
  { song: "그냥 (Just)", artist: "자이언티(Zion.T), 크러쉬 (CRUSH)" },
  { song: "Worth It (Feat. Kid Ink)", artist: "Fifth Harmony" },
  { song: "또 운다 또", artist: "다비치" },
  { song: "슬픔 속에 그댈 지워야만 해", artist: "정승환, 박윤하" },
  { song: "유리구슬 (Glass Bead)", artist: "여자친구 (GFRIEND)" },
  { song: "팔베개 (Pillow) (Feat. 기현)", artist: "소유, 기리보이 (Giriboy)" },
  { song: "환청 (Feat. 나쑈(NaShow))", artist: "장재인" },
  {
    song: "화 (Feat. 진실 of Mad Soul Child)",
    artist: "매드 클라운 (Mad Clown)",
  },
  { song: "목소리", artist: "노을" },
  { song: "Angel", artist: "윤미래, 타이거JK, 비지" },
  { song: "사랑에 빠지고 싶다", artist: "정승환" },
  { song: "니가 모르게 (You Don`t Know)", artist: "로꼬 (LOCO)" },
  { song: "Santa Tell Me", artist: "Ariana Grande" },
  { song: "LUV", artist: "에이핑크 (Apink)" },
  { song: "HAPPY TOGETHER", artist: "박효신" },
  { song: "GOOD BOY", artist: "GD X TAEYANG" },
  { song: "세 사람 (With 성시경)", artist: "토이 (Toy)" },
  { song: "Uptown Funk (Feat. Bruno Mars)", artist: "Mark Ronson" },
  { song: "사뿐사뿐 (Like a Cat)", artist: "AOA" },
  { song: "나는 달라 (Feat. BOBBY)", artist: "HI SUHYUN" },
  { song: "산다는 건 (Cheer Up)", artist: "홍진영" },
  { song: "내 생애 가장 행복한 시간 (Feat. 허각)", artist: "MC몽" },
  { song: "내가 그리웠니 (Feat. 진실 of Mad Soul Child)", artist: "MC몽" },
  { song: "언제쯤이면 (Duet.아이유)", artist: "윤현상" },
  { song: "SOFA", artist: "크러쉬 (CRUSH)" },
  {
    song: "BORN HATER (Feat. 빈지노, 버벌진트, B.I, MINO, BOBBY)",
    artist: "에픽하이 (Epik High)",
  },
  {
    song: "헤픈엔딩 (Feat. 조원선 of 롤러코스터)",
    artist: "에픽하이 (Epik High)",
  },
  { song: "0", artist: "비스트 (Beast)" },
  { song: "화장 지웠어 (Feat. Zion.T, HA:TFELT) (No make up)", artist: "개코" },
  { song: "시간과 낙엽", artist: "악동뮤지션 (AKMU)" },
  { song: "GDFR (Feat. Sage The Gemini And Lookas)", artist: "Flo Rida" },
  { song: "그게나야", artist: "김동률" },
  { song: "틈", artist: "소유, 권순일, 박용인" },
  { song: "손대지마", artist: "에일리 (Ailee)" },
  { song: "양화대교", artist: "자이언티(Zion.T)" },
  { song: "당신만이", artist: "곽진언, 김필, 임도혁" },
  { song: "위잉위잉", artist: "혁오 (hyukoh)" },
  { song: "너무 보고 싶어", artist: "어쿠스틱 콜라보" },
  { song: "독기", artist: "아이언" },
  { song: "묘해, 너와", artist: "어쿠스틱 콜라보" },
  { song: "Sugar", artist: "Maroon 5" },
  { song: "Animals", artist: "Maroon 5" },
  { song: "연결고리#힙합", artist: "바비 (BOBBY)" },
  {
    song: "사랑하긴 했었나요 스쳐가는 인연이었나요 짧지않은 우리 함께했던 시간들이 자꾸 내 마음을 가둬두네",
    artist: "잔나비",
  },
  { song: "위아래", artist: "EXID" },
  { song: "너를 사랑해", artist: "윤미래 (T)" },
  { song: "I Swear", artist: "씨스타 (Sistar)" },
  { song: "Best Mistake (Feat. Big Sean)", artist: "Ariana Grande" },
  { song: "공허해", artist: "WINNER" },
  { song: "끼부리지마", artist: "WINNER" },
  { song: "예뻐졌다 (feat. 지코 Of 블락비)", artist: "박보람" },
  { song: "잠 못드는 밤 (feat. 펀치(Punch))", artist: "크러쉬 (CRUSH)" },
  { song: "괜찮아 사랑이야", artist: "다비치" },
  { song: "Bang Bang", artist: "Jessie J, Ariana Grande, Nicki Minaj" },
  { song: "HER", artist: "블락비(Block B)" },
  { song: "최고의 행운", artist: "첸 (CHEN)" },
  { song: "Touch my body", artist: "씨스타 (Sistar)" },
  { song: "Lost Stars", artist: "Adam Levine" },
  { song: "No One Else Like You", artist: "Adam Levine" },
  { song: "Tell Me If You Wanna Go Home", artist: "Keira Knightley" },
  { song: "Darling", artist: "걸스데이(Girl`s Day)" },
  { song: "A Step You Can`t Take Back", artist: "Keira Knightley" },
  { song: "Like A Fool", artist: "Keira Knightley" },
  { song: "A Higher Place", artist: "Adam Levine" },
  { song: "Lost Stars", artist: "Keira Knightley" },
  { song: "이제 그만 싸우자", artist: "허각,정은지" },
  { song: "애타는 마음", artist: "울랄라세션, 아이유(IU)" },
  { song: "오늘부터 1일 (Day 1)", artist: "케이윌 (K.Will)" },
  { song: "Thinking Out Loud", artist: "Ed Sheeran" },
  { song: "Photograph", artist: "Ed Sheeran" },
  { song: "단발머리 (Short Hair)", artist: "AOA" },
  { song: "Maps", artist: "Maroon 5" },
  { song: "Good Luck", artist: "비스트 (Beast)" },
  { song: "한여름밤의 꿀", artist: "산이(San E), 레이나" },
  { song: "잊혀지다 (Feat. 양다일)", artist: "정키 (Jung key)" },
  { song: "나 왜이래", artist: "산이 (San E)" },
  { song: "I`m Not The Only One", artist: "Sam Smith" },
  { song: "사람냄새", artist: "Gary (개리), 정인" },
  { song: "Stay With Me", artist: "Sam Smith" },
  { song: "Lay Me Down", artist: "Sam Smith" },
  { song: "너를 너를 너를", artist: "플라이 투 더 스카이 (Fly To The Sky)" },
  { song: "너의 의미 (Feat. 김창완)", artist: "아이유 (IU)" },
  { song: "나의 옛날 이야기", artist: "아이유 (IU)" },
  { song: "너를 원해 (Feat. Beenzino)", artist: "정기고 (Junggigo)" },
  { song: "미운오리새끼", artist: "god" },
  { song: "중독 (Overdose)", artist: "EXO-K" },
  { song: "Problem (Feat. Iggy Azalea)", artist: "Ariana Grande" },
  { song: "너 사용법", artist: "에디킴" },
  { song: "Bad (Feat. Vassy) (Radio Edit)", artist: "David Guetta & Showtek" },
  { song: "2", artist: "악동뮤지션 (AKMU)" },
  { song: "Give Love", artist: "악동뮤지션 (AKMU)" },
  { song: "인연", artist: "윤민수, 신용재" },
  { song: "견딜만해 (Feat. 효린)", artist: "매드 클라운 (Mad Clown)" },
  { song: "가끔", artist: "크러쉬 (CRUSH)" },
  { song: "Mr. Chu (On Stage)", artist: "에이핑크 (Apink)" },
  { song: "그 중에 그대를 만나", artist: "이선희" },
  { song: "흔한 노래", artist: "임창정" },
  { song: "감아 (Feat. Crush)", artist: "로꼬 (LOCO)" },
  { song: "까탈레나 (Catallena)", artist: "오렌지 캬라멜 (Orange Caramel)" },
  { song: "Come Back Home", artist: "2NE1 (투애니 원)" },
  { song: "Mr.Mr.", artist: "소녀시대" },
  { song: "보름달 (Feat. Lena)", artist: "선미" },
  { song: "너의 모든 순간", artist: "성시경" },
  { song: "썸 (Feat. 릴보이 Of 긱스)", artist: "소유, 정기고" },
  { song: "안녕", artist: "효린" },
  { song: "짧은 치마 (Miniskirt)", artist: "AOA" },
  { song: "Something", artist: "걸스데이 (Girl`s Day)" },
  { song: "그대가 분다", artist: "엠씨더맥스 (M.C The Max)" },
  {
    song: "Happy (Gru`s Theme From Despicable Me 2)",
    artist: "Pharrell Williams",
  },
  { song: "My Destiny", artist: "린 (LYn)" },
  { song: "금요일에 만나요 (Feat. 장이정)", artist: "아이유 (IU)" },
  { song: "Dali, Van, Picasso", artist: "빈지노 (Beenzino)" },
  { song: "겨울 고백", artist: "성시경, 박효신, 서인국, 빅스 (VIXX), 여동생" },
  { song: "12월의 기적 (Miracles in December)", artist: "EXO" },
  { song: "Love Is An Open Door", artist: "Kristen Bell, Santino Fontana" },
  { song: "How Long Will I Love You", artist: "Ellie Goulding" },
  { song: "거짓말 거짓말 거짓말", artist: "이적" },
  { song: "너에게", artist: "성시경" },
  { song: "분홍신", artist: "아이유 (IU)" },
  { song: "처음엔 사랑이란게", artist: "버스커 버스커 (Busker Busker)" },
  { song: "나란놈이란", artist: "임창정" },
  {
    song: "착해 빠졌어 (Stupid In Love)",
    artist: "소유, 매드 클라운 (Mad Clown)",
  },
  { song: "삐딱하게 (Crooked)", artist: "G-Dragon" },
  { song: "Touch Love", artist: "윤미래 (T)" },
  { song: "갖고놀래 (Feat. 다이나믹 듀오)", artist: "범키" },
  { song: "으르렁 (Growl)", artist: "EXO" },
  { song: "아는사람 얘기", artist: "산이 (San E)" },
  { song: "아모르 파티", artist: "김연자" },
  { song: "U & I", artist: "에일리 (Ailee)" },
  { song: "NoNoNo", artist: "에이핑크 (Apink)" },
  { song: "오늘따라 보고싶어서 그래", artist: "다비치" },
  { song: "Baaam (Feat. Muzie)", artist: "다이나믹 듀오 (Dynamic Duo)" },
  { song: "빠빠빠", artist: "크레용팝 (Crayon Pop)" },
  { song: "My Love", artist: "이승철" },
  { song: "All Right", artist: "김예림 (투개월)" },
  { song: "Give It To Me", artist: "씨스타 (Sistar)" },
  {
    song: "넌 너무 야해 (The Way You Make Me Melt) (Feat. 긱스)",
    artist: "씨스타 (Sistar)",
  },
  { song: "너 하나야", artist: "포맨 (4Men)" },
  { song: "미친연애 (Bad Girl) (Feat. E-Sens)", artist: "범키" },
  { song: "짧은머리", artist: "허각, 정은지 (에이핑크)" },
  { song: "Bad Girls", artist: "이효리" },
  { song: "잘 있나요", artist: "더 원 (The One)" },
  { song: "청혼하는 거예요", artist: "포맨 (4Men)" },
  { song: "미스코리아", artist: "이효리" },
  { song: "꼭 한번 만나고 싶다", artist: "바이브 (Vibe)" },
  { song: "Yoo Hoo", artist: "시크릿 (Secret)" },
  { song: "Wash Away (Feat. 에일리)", artist: "긱스 (Geeks)" },
  { song: "이름이 뭐예요?", artist: "포미닛 (4Minute)" },
  { song: "I Love You", artist: "악동뮤지션 (AKMU)" },
  { song: "Hello (Feat. 버벌진트)", artist: "조용필" },
  { song: "Bounce", artist: "조용필" },
  { song: "Gentleman", artist: "싸이 (Psy)" },
  { song: "오늘 밤 (Feat. 배치기)", artist: "린 (LYn)" },
  { song: "좋아 (Joah)", artist: "박재범" },
  { song: "Somebody", artist: "15& (박지민, 백예린)" },
  { song: "Love Blossom (러브블러썸)", artist: "케이윌 (K.Will)" },
  { song: "외국인의 고백", artist: "악동뮤지션 (AKMU)" },
  { song: "어때 (Feat. 하림)", artist: "긱스 (Geeks)" },
  { song: "녹는 중 (Feat. 버벌진트)", artist: "다비치" },
  {
    song: "The Bad Touch (Gordon & Doyle Edit)",
    artist: "DJ Gollum Vs. EmpyreOne",
  },
  { song: "Rose", artist: "이하이" },
  { song: "Counting Stars", artist: "OneRepublic" },
  { song: "Man In Love (남자가 사랑할때)", artist: "인피니트 (Infinite)" },
  { song: "기대해", artist: "걸스데이 (Girl`s Day)" },
  { song: "그리고 하나", artist: "태연 (TAEYEON)" },
  { song: "Crescendo (크레셴도)", artist: "악동뮤지션 (AKMU)" },
  { song: "It`s Over", artist: "이하이" },
  { song: "어느 봄날", artist: "2AM" },
  { song: "거북이", artist: "다비치" },
  { song: "눈꽃", artist: "거미" },
  { song: "긴 생머리 그녀 (Miss Right)", artist: "틴 탑 (Teen Top)" },
  {
    song: "이게 사랑이 아니면 (Feat. 에일리)",
    artist: "버벌진트 (Verbal Jint)",
  },
  { song: "겨울사랑", artist: "더 원 (The One)" },
  { song: "Dream Girl", artist: "샤이니 (SHINee)" },
  { song: "모르시나요", artist: "다비치" },
  { song: "1440", artist: "허각" },
  { song: "있다 없으니까 (Gone Not Around Any Longer)", artist: "씨스타19" },
  { song: "안녕 나야", artist: "포맨 (4Men)" },
  { song: "눈물 (Feat. 유진)", artist: "리쌍" },
  { song: "모노드라마", artist: "허각, 유승우" },
  { song: "눈물샤워 (Feat. 에일리)", artist: "배치기" },
  { song: "I’m Sorry", artist: "씨엔블루 (CNBLUE)" },
  { song: "Special Girl (Feat. Bumkey)", artist: "인피니트H" },
  { song: "시작이 좋아 (Feat. 강민희)", artist: "버벌진트 (Verbla Jint)" },
  { song: "강북멋쟁이", artist: "정형돈" },
  { song: "싫다", artist: "백지영" },
  { song: "I Got A Boy", artist: "소녀시대" },
  { song: "혼자라고 생각말기", artist: "김보경" },
  { song: "Dancing Queen", artist: "소녀시대" },
  { song: "Goodbye To Romance", artist: "써니힐 (Sunny Hill)" },
  { song: "매력있어", artist: "악동뮤지션 (AKMU)" },
  { song: "Treasure", artist: "Bruno Mars" },
  { song: "When I Was Your Man", artist: "Bruno Mars" },
  {
    song: "크리스마스니까",
    artist: "성시경, 박효신, 이석훈, 서인국, 빅스 (VIXX)",
  },
  { song: "Talk That", artist: "시크릿 (Secret)" },
  { song: "카페인", artist: "양요섭" },
  { song: "다리꼬지마", artist: "악동뮤지션 (AKMU)" },
  { song: "되돌리다", artist: "이승기" },
  { song: "허수아비", artist: "이하이" },
  { song: "나쁜 사람", artist: "주니엘 (Juniel)" },
  { song: "힐링이 필요해", artist: "로이킴" },
  { song: "하지 못한 말", artist: "노을" },
  { song: "만약에 말야 (전우성 Solo)", artist: "노을" },
  { song: "Officially Missing You, Too", artist: "긱스 (Geeks), 소유" },
  { song: "? (물음표) (Feat. 최자, Zion.T)", artist: "프라이머리 (Primary)" },
  { song: "씨스루 (Feat. Zion.T, 개코)", artist: "프라이머리 (Primary)" },
  { song: "똑같은 사랑 똑같은 이별", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "1,2,3,4 (원,투,쓰리,포)", artist: "이하이" },
  { song: "귀여워", artist: "별, 권정열 (10cm)" },
  { song: "독 (Feat. E-Sens)", artist: "프라이머리 (Primary)" },
  { song: "휘파람", artist: "로이킴" },
  { song: "Ice Cream", artist: "현아 (HyunA)" },
  { song: "닐리리맘보", artist: "블락비 (Block B)" },
  { song: "저녁 하늘", artist: "에일리 (Ailee)" },
  { song: "먼지가 되어", artist: "로이킴, 정준영" },
  { song: "남자 없이 잘 살아", artist: "Miss A" },
  { song: "My Son", artist: "유승우" },
  { song: "말리꽃 (원곡가수 이승철)", artist: "이정" },
  { song: "이러지마 제발 (Please Don`t...)", artist: "케이윌 (K.Will)" },
  { song: "Fine Thank You And You", artist: "10cm" },
  { song: "춥다 (Feat. 이하이)", artist: "에픽하이 (Epik High)" },
  { song: "피어나", artist: "가인 (브라운 아이드 걸스)" },
  { song: "아마추어", artist: "이승철" },
  { song: "사랑은 눈꽃처럼", artist: "XIA(준수)" },
  { song: "Missing You (Feat. 김윤아)", artist: "G-Dragon" },
  { song: "크레용 (Crayon)", artist: "G-Dragon" },
  { song: "그XX", artist: "G-Dragon" },
  { song: "아프다", artist: "허각" },
  { song: "Poison", artist: "시크릿 (Secret)" },
  { song: "립스틱 (Lip Stick)", artist: "오렌지 캬라멜 (Orange Caramel)" },
  { song: "좋겠어 (I Wish)", artist: "FTISLAND (FT 아일랜드)" },
  { song: "느린노래", artist: "백아연" },
  { song: "니가 싫어", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "Sexy Love", artist: "티아라 (T-ara)" },
  { song: "우리 사랑 이대로", artist: "정은지 (에이핑크), 서인국" },
  { song: "홀로 (Feat. 김나영)", artist: "정키 (Jung Key)" },
  { song: "All For You", artist: "정은지 (에이핑크), 서인국" },
  { song: "Pandora", artist: "카라 (KARA)" },
  { song: "I Need You", artist: "허각, 지아 (Zia)" },
  { song: "달빛바다", artist: "아이유 (IU), 피에스타(FIESTAR)" },
  { song: "남자도 우나요", artist: "다비치" },
  { song: "가수가 된 이유", artist: "신용재" },
  { song: "자꾸만 자꾸만", artist: "신용재" },
  { song: "Only One", artist: "보아 (BoA)" },
  { song: "아름다운 밤이야", artist: "비스트 (Beast)" },
  { song: "한여름밤의 꿈", artist: "브라운 아이드 걸스" },
  { song: "어땠을까 (Feat. 박정현)", artist: "싸이 (Psy)" },
  { song: "강남스타일", artist: "싸이 (Psy)" },
  { song: "뜨거운 안녕 (Feat. 성시경)", artist: "싸이 (Psy)" },
  { song: "Midnight (별 헤는 밤)", artist: "비스트 (Beast)" },
  { song: "77학개론 (Feat. 리쌍, 김진표)", artist: "싸이 (Psy)" },
  { song: "청개구리 (Feat. G-Dragon)", artist: "싸이 (Psy)" },
  { song: "내 사랑아", artist: "이종현 (씨엔블루)" },
  { song: "방구석 날라리", artist: "처진 달팽이" },
  { song: "I Love You", artist: "2NE1 (투애니 원)" },
  { song: "Day By Day", artist: "티아라 (T-ara)" },
  { song: "Aqua Man", artist: "빈지노 (Beenzino)" },
  { song: "Boogie On & On", artist: "빈지노 (Beenzino)" },
  { song: "미안해서 미안해", artist: "김진표 (JP)" },
  { song: "Loving U (러빙유)", artist: "씨스타 (Sistar)" },
  { song: "안되겠더라", artist: "포맨 (4Men)" },
  { song: "Lucky Strike", artist: "Maroon 5" },
  { song: "한사람", artist: "허각" },
  { song: "One More Night", artist: "Maroon 5" },
  { song: "정말로 사랑한다면", artist: "버스커 버스커 (Busker Busker)" },
  {
    song: "그댈 마주하는건 힘들어 (그마힘)",
    artist: "버스커 버스커 (Busker Busker)",
  },
  { song: "충분히 예뻐", artist: "버벌진트 (Verbal Jint)" },
  { song: "소나기 (주르르루)", artist: "버스커 버스커 (Busker Busker)" },
  { song: "네온사인", artist: "버스커 버스커 (Busker Busker)" },
  { song: "Flashback", artist: "애프터스쿨(After School)" },
  { song: "가슴이 시린 게", artist: "이현 (에이트)" },
  { song: "굿바이데이", artist: "울랄라세션" },
  { song: "Electric Shock", artist: "f(x)" },
  { song: "illa illa (일라 일라)", artist: "주니엘 (Juniel)" },
  { song: "굿모닝 (Feat. 권정열)", artist: "버벌진트 (Verbal Jint)" },
  { song: "안좋을때 들으면 더 안좋은 노래", artist: "형돈이와 대준이" },
  { song: "Monster", artist: "빅뱅" },
  { song: "Like this", artist: "원더걸스 (Wonder Girls)" },
  { song: "STILL ALIVE", artist: "빅뱅" },
  { song: "입장정리 (Feat. 최자, Simon D)", artist: "프라이머리 (Primary)" },
  { song: "To You", artist: "틴 탑 (Teen Top)" },
  { song: "High High", artist: "김태우" },
  { song: "너에게 배운다 (My Love)", artist: "리쌍" },
  { song: "잘자요 굿나잇", artist: "비원에이포 (B1A4)" },
  { song: "Call You Mine (Feat. Geologic)", artist: "Jeff Bernat" },
  { song: "Groovin`", artist: "Jeff Bernat" },
  { song: "2HOT", artist: "지나(G.NA)" },
  { song: "If You Wonder", artist: "Jeff Bernat" },
  { song: "Good Boy (Feat. 용준형 of 비스트)", artist: "백지영" },
  { song: "추격자", artist: "인피니트 (Infinite)" },
  { song: "I 돈 Care (Feat. 서수민PD)", artist: "용감한 녀석들" },
  { song: "하루 끝", artist: "아이유 (IU)" },
  { song: "복숭아", artist: "아이유 (IU)" },
  { song: "아름다운 밤", artist: "울랄라세션" },
  { song: "나쁜놈 (Feat. 소야)", artist: "마이티 마우스 (Mighty Mouth)" },
  { song: "Hush", artist: "에이핑크 (Apink)" },
  { song: "목소리 (Feat. 개리)", artist: "백지영" },
  { song: "She`s Gone", artist: "디셈버 (December)" },
  { song: "Twinkle", artist: "소녀시대-태티서(Girls` Generation-TTS)" },
  { song: "너뿐이야 (You`re The One)", artist: "박진영" },
  {
    song: "다른 사람 품에 안겨서 (Someone else) Duet with 가인",
    artist: "박진영",
  },
  { song: "씨스루 (Feat. 개코, Zion.T)", artist: "프라이머리 (Primary)" },
  { song: "떠나간다", artist: "노을" },
  { song: "Payphone (Feat. Wiz Khalifa)", artist: "Maroon 5" },
  { song: "나혼자 (Alone)", artist: "씨스타 (Sistar)" },
  { song: "두 마리", artist: "배치기" },
  { song: "Volume Up", artist: "포미닛 (4minute)" },
  { song: "사랑은 다 그런거래요", artist: "양파, 다비치, HANNA" },
  { song: "여수 밤바다", artist: "버스커 버스커 (Busker Busker)" },
  { song: "꽃송이가", artist: "버스커 버스커 (Busker Busker)" },
  { song: "첫사랑", artist: "버스커 버스커 (Busker Busker)" },
  {
    song: "외로움 증폭장치 (브래드 드럼 한판 쉬기)",
    artist: "버스커 버스커 (Busker Busker)",
  },
  { song: "전활 거네", artist: "버스커 버스커 (Busker Busker)" },
  { song: "향수", artist: "버스커 버스커 (Busker Busker)" },
  { song: "골목길 어귀에서", artist: "버스커 버스커 (Busker Busker)" },
  { song: "미치게 보고싶은", artist: "태연 (TAEYEON)" },
  { song: "Hey You", artist: "씨엔블루 (CNBLUE)" },
  { song: "기다려 그리고 준비해", artist: "용감한 녀석들" },
  { song: "Venus", artist: "신화" },
  { song: "이상형", artist: "버스커 버스커 (Busker Busker)" },
  { song: "한참 지나서", artist: "백지영" },
  { song: "Sherlock.셜록 (Clue + Note)", artist: "샤이니 (SHINee)" },
  { song: "곰인형 (Feat. 해금)", artist: "린 (LYn)" },
  { song: "아직 사랑한다", artist: "씨엔블루 (CNBLUE)" },
  { song: "Love Day", artist: "양요섭, 정은지" },
  { song: "그대 한 사람", artist: "김수현" },
  { song: "너도 나처럼", artist: "2AM" },
  { song: "자니 (Feat. DYNAMICDUO)", artist: "프라이머리 (Primary)" },
  { song: "Call Me Maybe", artist: "Carly Rae Jepsen" },
  { song: "Fantastic Baby", artist: "빅뱅" },
  { song: "Blue", artist: "빅뱅" },
  { song: "BAD BOY", artist: "빅뱅" },
  { song: "사랑먼지", artist: "빅뱅" },
  { song: "재미없어", artist: "빅뱅" },
  { song: "Falling", artist: "존 박" },
  { song: "Touch", artist: "miss A" },
  { song: "잊었니", artist: "이승철" },
  { song: "니가 필요해 (I Need You)", artist: "케이윌 (K.Will)" },
  { song: "Heaven", artist: "에일리 (Ailee)" },
  { song: "Marry You", artist: "Bruno Mars" },
  { song: "생각날거야", artist: "다비치" },
  { song: "겁이나서 (With 백지영)", artist: "나윤권" },
  { song: "난리나", artist: "블락비 (Block B)" },
  { song: "내가 노래를 못해도", artist: "세븐 (SE7EN)" },
  { song: "지독하게", artist: "FTISLAND (FT 아일랜드)" },
  { song: "내가 싫다", artist: "케이윌 (K.Will)" },
  { song: "Hit U", artist: "Dal★Shabet (달샤벳)" },
  { song: "이럴 줄 알았어", artist: "비스트 (Beast)" },
  { song: "널 사랑하겠어", artist: "효린" },
  { song: "베짱이 찬가", artist: "써니힐 (SunnyHill)" },
  { song: "전쟁이야", artist: "엠블랙 (MBLAQ)" },
  { song: "Livin` My Love", artist: "LMFAO, Steve Aoki" },
  { song: "키 큰 노총각 이야기", artist: "정준하" },
  { song: "미치겠어", artist: "틴 탑 (Teen Top)" },
  { song: "거기서거기 (Without You)", artist: "다이나믹 듀오 (Dynamic Duo)" },
  { song: "Lovey-Dovey", artist: "티아라 (T-ara)" },
  { song: "속상해서 (술 한잔 해요 Part 2)", artist: "지아 (Zia)" },
  { song: "우리 사랑했잖아", artist: "다비치, 티아라" },
  { song: "촌스럽게 굴지마 (Feat. 용준형)", artist: "알리 (Ali)" },
  { song: "그 노래를 틀때마다", artist: "허각, LE(EXID)" },
  { song: "살기 위해서", artist: "노을" },
  { song: "Trouble Maker", artist: "트러블메이커 (Trouble Maker)" },
  { song: "너랑 나", artist: "아이유 (IU)" },
  { song: "비밀", artist: "아이유 (IU)" },
  { song: "삼촌 (Feat. 이적)", artist: "아이유 (IU)" },
  {
    song: "불타는 금요일 (Friday Night)",
    artist: "다이나믹 듀오 (Dynamic Duo)",
  },
  { song: "My My", artist: "에이핑크 (Apink)" },
  { song: "서울사람들", artist: "버스커 버스커 (Busker Busker)" },
  { song: "Ma Boy 2 (Feat. 효린)", artist: "일렉트로보이즈 (Electroboyz)" },
  { song: "Replay", artist: "김동률" },
  { song: "Cry Cry", artist: "티아라 (T-ara)" },
  { song: "사랑에 빠지고 싶다", artist: "김조한" },
  { song: "Be My Baby", artist: "원더걸스 (Wonder girls)" },
  { song: "죽고 싶단 말 밖에", artist: "허각" },
  { song: "Swing Baby", artist: "울랄라세션" },
  { song: "G.N.O.", artist: "원더걸스 (Wonder girls)" },
  { song: "그댄 달라요", artist: "버스커 버스커 (Busker Busker)" },
  { song: "클렌징크림", artist: "브라운아이드걸스" },
  { song: "그 남자 그 여자", artist: "포맨 (4Men), 미 (美)" },
  { song: "Tomorrow (Feat. 태양)", artist: "타블로" },
  { song: "막걸리나", artist: "버스커 버스커 (Busker Busker)" },
  {
    song: "Get It In (Feat. Tiger JK & 정인) (Korean Ver.)",
    artist: "윤미래 (T)",
  },
  { song: "그리워 그리워", artist: "노을" },
  { song: "친구잖아", artist: "이승기" },
  { song: "나쁘다 (Feat. 진실)", artist: "타블로" },
  { song: "The Boys", artist: "소녀시대" },
  { song: "Mr.Taxi (Korean Ver.)", artist: "소녀시대" },
  { song: "사랑은 Move", artist: "시크릿 (Secret)" },
  { song: "여기가 아파", artist: "백지영" },
  { song: "미인", artist: "울랄라세션" },
  { song: "Brown City", artist: "투개월" },
  { song: "연애시대 (Feat. Ra.D / Nar. 한효주)", artist: "이승기" },
  { song: "Airbag (Feat. 나얼)", artist: "타블로 (에픽하이)" },
  { song: "샹하이 로맨스 (上海之戀)", artist: "오렌지캬라멜 (Orange Caramel)" },
  { song: "그대와 나, 설레임", artist: "어쿠스틱 콜라보" },
  { song: "Open Arms (Journey) (Feat. 크리스티나)", artist: "울랄라세션" },
  { song: "Poker Face (Lady GaGa)", artist: "투개월" },
  { song: "사랑과 우정 사이 (피노키오) (with 김연우)", artist: "김경호" },
  { song: "동경소녀", artist: "버스커 버스커 (Busker Busker)" },
  { song: "여우야", artist: "투개월" },
  { song: "달의 몰락", artist: "울랄라세션" },
  { song: "내가 이렇지 (Feat. 하동균)", artist: "지아 (Zia)" },
  {
    song: "Sex Apeal (Max Farenthide Radio Edit) (Feat. Mike W.)",
    artist: "Bueno Clinic",
  },
  { song: "파라다이스 (Paradise)", artist: "인피니트 (Infinite)" },
  { song: "Sixth Sense", artist: "브라운 아이드 걸스" },
  { song: "Hot Shot", artist: "브라운 아이드 걸스" },
  { song: "난 좋아", artist: "성시경" },
  { song: "그대이길 바래요 (With 케이윌)", artist: "지아 (Zia)" },
  { song: "STEP", artist: "카라 (KARA)" },
  { song: "I Was Born To Love You", artist: "Queen" },
  { song: "좋아보여 (Feat. 검정치마)", artist: "버벌진트 (Verbal Jint)" },
  { song: "안녕이라고 말하지마", artist: "다비치" },
  { song: "사랑 사랑아", artist: "다비치" },
  { song: "나란 놈은 답은 너다 (Feat. 하림)", artist: "리쌍" },
  { song: "회상 (Feat. 백지영)", artist: "리쌍" },
  { song: "Top Girl", artist: "지나(G.NA)" },
  { song: "TV를 껐네...  (Feat. 윤미래, 권정열)", artist: "리쌍" },
  { song: "안아줘요", artist: "10cm" },
  { song: "가슴으로 운다 (Feat. 아이린, 윤미)", artist: "디셈버, 제이세라" },
  { song: "블링블링 (Bling Bling)", artist: "Dal★Shabet (달샤벳)" },
  { song: "So Cool (쏘쿨)", artist: "씨스타 (Sistar)" },
  { song: "You Are So Beautiful", artist: "김준수" },
  { song: "Mr. Simple", artist: "슈퍼주니어 (Super Junior)" },
  { song: "Ugly", artist: "2NE1 (투애니 원)" },
  { song: "Grand Final (Feat. 정인 & MC 날유)", artist: "리쌍" },
  { song: "나 가거든 (If I Leave) (조수미)", artist: "박정현" },
  { song: "술이야 (바이브)", artist: "장혜진" },
  { song: "Hate You", artist: "2NE1 (투애니 원)" },
  { song: "내꺼하자", artist: "인피니트 (Infinite)" },
  { song: "밤 하늘에", artist: "애프터스쿨 RED" },
  { song: "남자니까 웃는거야", artist: "창민, 이현 (HOMME)" },
  { song: "Good-bye Baby", artist: "miss A" },
  { song: "오늘도 사랑해", artist: "백지영" },
  { song: "모나리자 (Mona Lisa)", artist: "엠블랙 (MBLAQ)" },
  { song: "한번만 안아줘", artist: "걸스데이 (Girl`s Day)" },
  { song: "Bubble Pop!", artist: "현아 (HyunA)" },
  { song: "바람났어 (Feat. 박봄)", artist: "GG" },
  { song: "압구정 날라리", artist: "처진 달팽이" },
  { song: "나만 부를 수 있는 노래", artist: "바닷길" },
  { song: "흔들어 주세요", artist: "철싸" },
  { song: "순정마초", artist: "파리돼지앵" },
  { song: "말하는 대로", artist: "처진 달팽이" },
  { song: "정주나요", artist: "스윗 콧소로우" },
  { song: "죽을래 사귈래", artist: "센치한 하하" },
  { song: "찹쌀떡", artist: "센치한 하하" },
  { song: "다이어리", artist: "나비 (Navi)" },
  {
    song: "A Bitter Day (Feat. 용준형 of 비스트, G.NA)",
    artist: "현아 (HyunA)",
  },
  { song: "Roly-Poly", artist: "티아라 (T-ara)" },
  { song: "넌 내게 반했어", artist: "정용화(Jung Yong Hwa)" },
  { song: "랄랄라 (Feat. 소야)", artist: "마이티 마우스 (Mighty Mouth)" },
  { song: "Love On Top", artist: "Beyonce" },
  {
    song: "Moves Like Jagger (Feat. Christina Aguilera) (Studio Recording From The Voice Performance)",
    artist: "Maroon 5",
  },
  { song: "내가 제일 잘 나가", artist: "2NE1 (투애니 원)" },
  { song: "Sweet Dream", artist: "레인보우 (Rainbow)" },
  { song: "그 입술을 막아본다", artist: "에이트 (8eight)" },
  { song: "얼음꽃 (Feat. 김세황)", artist: "아이유 (IU), 김연아" },
  { song: "Hands Up", artist: "2PM" },
  { song: "바보 (박효신)", artist: "박정현" },
  { song: "Hot Summer", artist: "f(x)" },
  { song: "조율", artist: "JK 김동욱" },
  { song: "그렇고 그런 사이", artist: "장기하와 얼굴들" },
  { song: "살다가 한번쯤", artist: "포맨 (4Men)" },
  { song: "Midnight Circus", artist: "써니힐 (SunnyHill)" },
  { song: "별빛달빛", artist: "시크릿 (Secret)" },
  { song: "나를 잊지 말아요", artist: "허각" },
  { song: "천일동안 (이승환)", artist: "옥주현" },
  { song: "내 손을 잡아", artist: "아이유 (IU)" },
  { song: "Hello Hello", artist: "FTISLAND (FT 아일랜드)" },
  { song: "나와 같다면 (김장훈)", artist: "김연우" },
  { song: "늪 (조관우)", artist: "김범수" },
  { song: "여러분 (윤복희)", artist: "임재범" },
  { song: "사랑", artist: "임재범" },
  { song: "보통", artist: "백지영" },
  { song: "두근두근", artist: "써니힐 (SunnyHill)" },
  { song: "Fiction", artist: "비스트 (Beast)" },
  { song: "그날에 우리", artist: "어반 자카파 (Urban Zakapa)" },
  { song: "비가 오는 날엔", artist: "비스트 (Beast)" },
  { song: "Lonely", artist: "2NE1 (투애니 원)" },
  { song: "이러쿵 저러쿵", artist: "5dolls" },
  { song: "내 사람이라서", artist: "지나(G.NA)" },
  { song: "Golden Lady (Feat. 현아)", artist: "임정희" },
  { song: "이젠 그랬으면 좋겠네 (조용필)", artist: "박정현" },
  { song: "미련 (김건모)", artist: "김연우" },
  { song: "미인", artist: "디셈버 (December)" },
  { song: "Ma Boy (마보이)", artist: "씨스타19" },
  { song: "Love Alone", artist: "miss A" },
  { song: "Shampoo", artist: "애프터스쿨 (After School)" },
  { song: "Don`t Cry", artist: "박봄" },
  { song: "피노키오 (Danger)", artist: "f(x)" },
  { song: "몰라요", artist: "에이핑크 (Apink)" },
  {
    song: "배가 불렀지 (Feat. GaeKo Of DYNAMIC DUO)",
    artist: "슈프림팀 (Supreme Team)",
  },
  { song: "들리나요", artist: "지아 (Zia)" },
  { song: "별 짓 다해봤는데", artist: "알리 (Ali)" },
  { song: "다며 (Feat. 마이티마우스)", artist: "이현 (에이트)" },
  { song: "LOVE SONG", artist: "빅뱅" },
  { song: "STUPID LIAR", artist: "빅뱅" },
  { song: "To Me (내게로..)", artist: "레인보우 (Rainbow)" },
  { song: "너 밖엔 없더라", artist: "김그림" },
  { song: "거울아 거울아", artist: "포미닛 (4minute)" },
  { song: "방콕시티 (Bangkok City)", artist: "오렌지 캬라멜 (Orange Caramel)" },
  { song: "La Vida Loca", artist: "클로버 (Clover)" },
  { song: "Heart To Heart", artist: "포미닛 (4minute)" },
  { song: "메아리", artist: "김태우" },
  { song: "아파 아이야", artist: "양파" },
  { song: "이태원 프리덤 (With JYP)", artist: "유브이 (UV)" },
  { song: "제발", artist: "김범수" },
  { song: "약속", artist: "백지영" },
  { song: "You Are My Lady", artist: "김건모" },
  { song: "Dash (With YB)", artist: "윤도현" },
  { song: "첫인상", artist: "박정현" },
  { song: "아무일도 없었다", artist: "정엽" },
  { song: "직감", artist: "씨엔블루 (CNBLUE)" },
  { song: "나 항상 그대를 (With YB)", artist: "윤도현" },
  { song: "반짝반짝", artist: "걸스데이 (Girl`s Day)" },
  { song: "가슴 시린 이야기 (Feat. 용준형)", artist: "휘성" },
  { song: "가슴이 뛴다", artist: "케이윌 (K.Will)" },
  { song: "가질 수 없는 너", artist: "현빈" },
  { song: "미친거니 (Feat. 방용국)", artist: "송지은" },
  { song: "Tonight", artist: "빅뱅" },
  { song: "Cafe", artist: "빅뱅" },
  { song: "What Is Right", artist: "빅뱅" },
  { song: "나만 몰랐던 이야기", artist: "아이유 (IU)" },
  { song: "파파라치 (Feat. 에릭)", artist: "간미연" },
  { song: "Just The Way You Are", artist: "Bruno Mars" },
  { song: "내꺼중에 최고", artist: "이현 (에이트)" },
  { song: "사랑은 은하수 다방에서", artist: "10cm" },
  {
    song: "Party Rock Anthem (Feat. Lauren Bennett, Goon Rock)",
    artist: "LMFAO",
  },
  { song: "Someone Like You", artist: "Adele" },
  { song: "Rolling In The Deep", artist: "Adele" },
  { song: "Black & White", artist: "지나(G.NA)" },
  {
    song: "톡톡 (Tok Tok) (Feat. Soya)",
    artist: "마이티 마우스 (Mighty Mouth)",
  },
  { song: "Bohemian Rhapsody (2011 Remaster)", artist: "Queen" },
  { song: "좋은 날", artist: "아이유 (IU)" },
  { song: "미리 메리 크리스마스 (Feat. 천둥)", artist: "아이유 (IU)" },
  { song: "Love The Way You Lie (Part II) (Feat. Eminem)", artist: "Rihanna" },
  {
    song: "I Got My Eye On You (Cristian Marchi & Paolo Sandrini Perfect Edit) (Feat. Luciana)",
    artist: "Nari & Milani, Cristian Marchi",
  },
  {
    song: "그땐 그땐 그땐",
    artist: "슈프림팀 (Supreme Team), 영준 (브라운 아이드 소울)",
  },
  { song: "널 생각해", artist: "원 모어 찬스 (One More Chance)" },
  { song: "아메리카노", artist: "10cm" },
  { song: "Love The Way You Lie (Feat. Rihanna)", artist: "Eminem" },
  { song: "못해 (Feat. 美)", artist: "포맨 (4Men)" },
  {
    song: "헤어지지 못하는 여자, 떠나가지 못하는 남자 (Feat. 정인)",
    artist: "리쌍",
  },
  { song: "Empire State Of Mind (Feat. Alicia Keys)", artist: "Jay-Z" },
  { song: "Halo", artist: "Beyonce" },
  { song: "Viva La Vida", artist: "Coldplay" },
  { song: "Slow Motion", artist: "Karina" },
  { song: "Lucky (Feat. Colbie Caillat)", artist: "Jason Mraz" },
  { song: "I`m Yours", artist: "Jason Mraz" },
  { song: "I`m Yours (Album Version)", artist: "Jason Mraz" },
  { song: "Falling Slowly", artist: "Glen Hansard, Marketa lrglova" },
  { song: "추억은 사랑을 닮아", artist: "박효신" },
  { song: "거리에서", artist: "성시경" },
  { song: "서쪽 하늘", artist: "이승철" },
  { song: "광대", artist: "리쌍, BMK" },
  { song: "Fix You", artist: "Coldplay" },
  { song: "인연 (동녘바람)", artist: "이선희" },
  { song: "바람이 분다", artist: "이소라" },
  { song: "Sunday Morning", artist: "Maroon 5" },
  { song: "너에게 쓰는 편지", artist: "MC 몽" },
  { song: "The Scientist", artist: "Coldplay" },
  { song: "Don`t Know Why", artist: "Norah Jones" },
  { song: "여전히 아름다운지 (Feat. 김연우)", artist: "토이 (Toy)" },
];

module.exports = sampleSongs;
